// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_decimation_filter_fir_decimation_filter,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.471000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=334,HLS_SYN_LUT=411,HLS_VERSION=2022_1}" *)

module fir_decimation_filter (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input  [7:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [0:0] input_r_TKEEP;
input  [0:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [31:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [3:0] output_r_TKEEP;
output  [3:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [2:0] count_V;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7;
reg   [7:0] p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3;
reg   [31:0] sum_V;
reg    input_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln1065_fu_606_p2;
wire    ap_CS_fsm_state7;
reg   [0:0] icmp_ln1065_reg_787;
reg   [0:0] tmp_last_V_reg_673;
wire  signed [32:0] sext_ln42_fu_192_p1;
reg  signed [32:0] sext_ln42_reg_681;
wire   [7:0] r_V_7_fu_216_p7;
reg  signed [7:0] r_V_7_reg_688;
wire  signed [7:0] r_V_3_fu_322_p7;
reg  signed [7:0] r_V_3_reg_696;
wire  signed [7:0] r_V_fu_388_p7;
reg  signed [7:0] r_V_reg_701;
wire    ap_CS_fsm_state2;
wire   [15:0] tmp_6_fu_534_p7;
reg  signed [15:0] tmp_6_reg_736;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [24:0] grp_fu_656_p3;
reg  signed [24:0] add_ln859_reg_771;
wire    ap_CS_fsm_state5;
wire  signed [24:0] grp_fu_648_p3;
wire   [31:0] output_temp_data_V_fu_599_p2;
reg   [31:0] output_temp_data_V_reg_781;
reg   [31:0] ap_phi_mux_sum_V_new_0_phi_fu_163_p4;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
reg    ap_block_state7;
reg    ap_block_state7_io;
wire   [2:0] add_ln886_fu_611_p2;
reg    ap_block_state6;
reg    ap_block_state6_io;
wire  signed [7:0] r_V_5_fu_256_p7;
wire   [2:0] trunc_ln42_fu_232_p1;
wire   [3:0] count_V_load_cast_fu_182_p1;
wire  signed [3:0] sub_i_i220_fu_186_p2;
wire  signed [15:0] tmp_4_fu_468_p7;
wire  signed [15:0] tmp_7_fu_492_p7;
wire  signed [15:0] tmp_5_fu_515_p7;
wire  signed [15:0] tmp_8_fu_552_p7;
wire  signed [23:0] grp_fu_634_p2;
wire  signed [23:0] grp_fu_641_p2;
wire  signed [31:0] sext_ln859_1_fu_587_p1;
wire  signed [24:0] grp_fu_664_p3;
wire  signed [31:0] sext_ln859_2_fu_596_p1;
wire   [31:0] add_ln859_1_fu_590_p2;
reg    grp_fu_634_ce;
reg    grp_fu_641_ce;
reg    grp_fu_664_ce;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire  signed [7:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [0:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [0:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire   [31:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 count_V = 3'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7 = 8'd0;
#0 p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3 = 8'd0;
#0 sum_V = 32'd0;
#0 ap_CS_fsm = 7'd1;
end

fir_decimation_filter_mux_533_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 8 ))
mux_533_8_1_1_U1(
    .din0(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16),
    .din1(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12),
    .din2(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8),
    .din3(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4),
    .din4(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E),
    .din5(sext_ln42_fu_192_p1),
    .dout(r_V_7_fu_216_p7)
);

fir_decimation_filter_mux_533_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 8 ))
mux_533_8_1_1_U2(
    .din0(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17),
    .din1(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13),
    .din2(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9),
    .din3(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5),
    .din4(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1),
    .din5(sext_ln42_fu_192_p1),
    .dout(r_V_5_fu_256_p7)
);

fir_decimation_filter_mux_533_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 8 ))
mux_533_8_1_1_U3(
    .din0(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18),
    .din1(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14),
    .din2(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10),
    .din3(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6),
    .din4(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2),
    .din5(sext_ln42_fu_192_p1),
    .dout(r_V_3_fu_322_p7)
);

fir_decimation_filter_mux_533_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 8 ))
mux_533_8_1_1_U4(
    .din0(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19),
    .din1(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15),
    .din2(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11),
    .din3(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7),
    .din4(p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3),
    .din5(sext_ln42_fu_192_p1),
    .dout(r_V_fu_388_p7)
);

fir_decimation_filter_mux_533_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_533_16_1_1_U5(
    .din0(16'd65463),
    .din1(16'd65309),
    .din2(16'd65438),
    .din3(16'd249),
    .din4(16'd625),
    .din5(sext_ln42_fu_192_p1),
    .dout(tmp_4_fu_468_p7)
);

fir_decimation_filter_mux_533_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_533_16_1_1_U6(
    .din0(16'd630),
    .din1(16'd63994),
    .din2(16'd63974),
    .din3(16'd65078),
    .din4(16'd465),
    .din5(sext_ln42_fu_192_p1),
    .dout(tmp_7_fu_492_p7)
);

fir_decimation_filter_mux_533_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_533_16_1_1_U7(
    .din0(16'd465),
    .din1(16'd65078),
    .din2(16'd63974),
    .din3(16'd63994),
    .din4(16'd630),
    .din5(sext_ln42_reg_681),
    .dout(tmp_5_fu_515_p7)
);

fir_decimation_filter_mux_533_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_533_16_1_1_U8(
    .din0(16'd4623),
    .din1(16'd8572),
    .din2(16'd10222),
    .din3(16'd8572),
    .din4(16'd4623),
    .din5(sext_ln42_reg_681),
    .dout(tmp_6_fu_534_p7)
);

fir_decimation_filter_mux_533_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_533_16_1_1_U9(
    .din0(16'd625),
    .din1(16'd249),
    .din2(16'd65438),
    .din3(16'd65309),
    .din4(16'd65463),
    .din5(sext_ln42_reg_681),
    .dout(tmp_8_fu_552_p7)
);

fir_decimation_filter_mul_mul_16s_8s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8s_24_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_4_fu_468_p7),
    .din1(input_r_TDATA_int_regslice),
    .ce(grp_fu_634_ce),
    .dout(grp_fu_634_p2)
);

fir_decimation_filter_mul_mul_16s_8s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8s_24_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_7_fu_492_p7),
    .din1(r_V_5_fu_256_p7),
    .ce(grp_fu_641_ce),
    .dout(grp_fu_641_p2)
);

fir_decimation_filter_mac_muladd_16s_8s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8s_24s_25_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_5_fu_515_p7),
    .din1(r_V_reg_701),
    .din2(grp_fu_634_p2),
    .ce(1'b1),
    .dout(grp_fu_648_p3)
);

fir_decimation_filter_mac_muladd_16s_8s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8s_24s_25_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_8_fu_552_p7),
    .din1(r_V_7_reg_688),
    .din2(grp_fu_641_p2),
    .ce(1'b1),
    .dout(grp_fu_656_p3)
);

fir_decimation_filter_mac_muladd_16s_8s_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8s_25s_25_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_6_reg_736),
    .din1(r_V_3_reg_696),
    .din2(grp_fu_648_p3),
    .ce(grp_fu_664_ce),
    .dout(grp_fu_664_p3)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

fir_decimation_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_673),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_fu_606_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        count_V <= add_ln886_fu_611_p2;
    end else if ((~((1'b1 == ap_block_state7_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_reg_787 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        count_V <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln859_reg_771 <= grp_fu_656_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln1065_reg_787 <= icmp_ln1065_fu_606_p2;
        output_temp_data_V_reg_781 <= output_temp_data_V_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln42_fu_232_p1 == 3'd3) & ~(trunc_ln42_fu_232_p1 == 3'd2) & ~(trunc_ln42_fu_232_p1 == 3'd1) & ~(trunc_ln42_fu_232_p1 == 3'd0) & (input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E <= r_V_5_fu_256_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1 <= r_V_3_fu_322_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2 <= r_V_fu_388_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln42_fu_232_p1 == 3'd2))) begin
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10 <= r_V_fu_388_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11 <= input_r_TDATA_int_regslice;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8 <= r_V_5_fu_256_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9 <= r_V_3_fu_322_p7;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln42_fu_232_p1 == 3'd1))) begin
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12 <= r_V_5_fu_256_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13 <= r_V_3_fu_322_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14 <= r_V_fu_388_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln42_fu_232_p1 == 3'd0))) begin
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16 <= r_V_5_fu_256_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17 <= r_V_3_fu_322_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18 <= r_V_fu_388_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln42_fu_232_p1 == 3'd3))) begin
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4 <= r_V_5_fu_256_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5 <= r_V_3_fu_322_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6 <= r_V_fu_388_p7;
        p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        r_V_3_reg_696 <= r_V_3_fu_322_p7;
        r_V_7_reg_688 <= r_V_7_fu_216_p7;
        r_V_reg_701 <= r_V_fu_388_p7;
        sext_ln42_reg_681 <= sext_ln42_fu_192_p1;
        tmp_last_V_reg_673 <= input_r_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state7_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state7))) begin
        sum_V <= ap_phi_mux_sum_V_new_0_phi_fu_163_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_6_reg_736 <= tmp_6_fu_534_p7;
    end
end

always @ (*) begin
    if ((input_r_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state7_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((icmp_ln1065_reg_787 == 1'd0)) begin
            ap_phi_mux_sum_V_new_0_phi_fu_163_p4 = output_temp_data_V_reg_781;
        end else if ((icmp_ln1065_reg_787 == 1'd1)) begin
            ap_phi_mux_sum_V_new_0_phi_fu_163_p4 = 32'd0;
        end else begin
            ap_phi_mux_sum_V_new_0_phi_fu_163_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_sum_V_new_0_phi_fu_163_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_634_ce = 1'b1;
    end else begin
        grp_fu_634_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_641_ce = 1'b1;
    end else begin
        grp_fu_641_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (~((1'b1 == ap_block_state6_io) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_664_ce = 1'b1;
    end else begin
        grp_fu_664_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1065_reg_787 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_fu_606_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((1'b1 == ap_block_state7_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln859_1_fu_590_p2 = ($signed(sext_ln859_1_fu_587_p1) + $signed(sum_V));

assign add_ln886_fu_611_p2 = (count_V + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state6 = ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((icmp_ln1065_fu_606_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state7_io = ((icmp_ln1065_reg_787 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign count_V_load_cast_fu_182_p1 = count_V;

assign icmp_ln1065_fu_606_p2 = ((count_V == 3'd4) ? 1'b1 : 1'b0);

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign output_r_TDATA_int_regslice = ($signed(sext_ln859_2_fu_596_p1) + $signed(add_ln859_1_fu_590_p2));

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign output_temp_data_V_fu_599_p2 = ($signed(sext_ln859_2_fu_596_p1) + $signed(add_ln859_1_fu_590_p2));

assign sext_ln42_fu_192_p1 = sub_i_i220_fu_186_p2;

assign sext_ln859_1_fu_587_p1 = add_ln859_reg_771;

assign sext_ln859_2_fu_596_p1 = grp_fu_664_p3;

assign sub_i_i220_fu_186_p2 = (4'd4 - count_V_load_cast_fu_182_p1);

assign trunc_ln42_fu_232_p1 = sub_i_i220_fu_186_p2[2:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "fir_decimation_filter_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fir_decimation_filter

