-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity quadrature_demodulator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    real_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    real_r_TVALID : IN STD_LOGIC;
    real_r_TREADY : OUT STD_LOGIC;
    real_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    real_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    real_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    imag_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_TVALID : IN STD_LOGIC;
    imag_TREADY : OUT STD_LOGIC;
    imag_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    imag_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    imag_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of quadrature_demodulator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "quadrature_demodulator_quadrature_demodulator,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=700,HLS_SYN_LUT=301,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal real_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal imag_TDATA_blk_n : STD_LOGIC;
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_data_V_1_reg_211 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_last_V_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_2_reg_221 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_real_V_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_real_V_reg_226 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_imag_V_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_imag_V_reg_231 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_178_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal r_V_1_reg_256 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_190_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal r_V_3_reg_261 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal diff_real_V_fu_160_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_imag_V_fu_166_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_fu_196_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal regslice_both_real_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal real_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal real_r_TVALID_int_regslice : STD_LOGIC;
    signal real_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_real_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal real_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal real_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal real_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_real_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_r_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_V_data_V_U_apdone_blk : STD_LOGIC;
    signal imag_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_TVALID_int_regslice : STD_LOGIC;
    signal imag_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_imag_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal imag_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal imag_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_V_last_V_U_apdone_blk : STD_LOGIC;
    signal imag_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_imag_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component quadrature_demodulator_mul_32s_32s_54_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;


    component quadrature_demodulator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mul_32s_32s_54_2_1_U1 : component quadrature_demodulator_mul_32s_32s_54_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => diff_imag_V_reg_231,
        din1 => tmp_data_V_1_reg_211,
        ce => ap_const_logic_1,
        dout => grp_fu_178_p2);

    mul_32s_32s_54_2_1_U2 : component quadrature_demodulator_mul_32s_32s_54_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => diff_real_V_reg_226,
        din1 => tmp_data_V_2_reg_221,
        ce => ap_const_logic_1,
        dout => grp_fu_190_p2);

    regslice_both_real_r_V_data_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_r_TDATA,
        vld_in => real_r_TVALID,
        ack_in => regslice_both_real_r_V_data_V_U_ack_in,
        data_out => real_r_TDATA_int_regslice,
        vld_out => real_r_TVALID_int_regslice,
        ack_out => real_r_TREADY_int_regslice,
        apdone_blk => regslice_both_real_r_V_data_V_U_apdone_blk);

    regslice_both_real_r_V_keep_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_r_TKEEP,
        vld_in => real_r_TVALID,
        ack_in => regslice_both_real_r_V_keep_V_U_ack_in,
        data_out => real_r_TKEEP_int_regslice,
        vld_out => regslice_both_real_r_V_keep_V_U_vld_out,
        ack_out => real_r_TREADY_int_regslice,
        apdone_blk => regslice_both_real_r_V_keep_V_U_apdone_blk);

    regslice_both_real_r_V_strb_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_r_TSTRB,
        vld_in => real_r_TVALID,
        ack_in => regslice_both_real_r_V_strb_V_U_ack_in,
        data_out => real_r_TSTRB_int_regslice,
        vld_out => regslice_both_real_r_V_strb_V_U_vld_out,
        ack_out => real_r_TREADY_int_regslice,
        apdone_blk => regslice_both_real_r_V_strb_V_U_apdone_blk);

    regslice_both_real_r_V_last_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_r_TLAST,
        vld_in => real_r_TVALID,
        ack_in => regslice_both_real_r_V_last_V_U_ack_in,
        data_out => real_r_TLAST_int_regslice,
        vld_out => regslice_both_real_r_V_last_V_U_vld_out,
        ack_out => real_r_TREADY_int_regslice,
        apdone_blk => regslice_both_real_r_V_last_V_U_apdone_blk);

    regslice_both_imag_V_data_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_TDATA,
        vld_in => imag_TVALID,
        ack_in => regslice_both_imag_V_data_V_U_ack_in,
        data_out => imag_TDATA_int_regslice,
        vld_out => imag_TVALID_int_regslice,
        ack_out => imag_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_V_data_V_U_apdone_blk);

    regslice_both_imag_V_keep_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_TKEEP,
        vld_in => imag_TVALID,
        ack_in => regslice_both_imag_V_keep_V_U_ack_in,
        data_out => imag_TKEEP_int_regslice,
        vld_out => regslice_both_imag_V_keep_V_U_vld_out,
        ack_out => imag_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_V_keep_V_U_apdone_blk);

    regslice_both_imag_V_strb_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_TSTRB,
        vld_in => imag_TVALID,
        ack_in => regslice_both_imag_V_strb_V_U_ack_in,
        data_out => imag_TSTRB_int_regslice,
        vld_out => regslice_both_imag_V_strb_V_U_vld_out,
        ack_out => imag_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_V_strb_V_U_apdone_blk);

    regslice_both_imag_V_last_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_TLAST,
        vld_in => imag_TVALID,
        ack_in => regslice_both_imag_V_last_V_U_ack_in,
        data_out => imag_TLAST_int_regslice,
        vld_out => regslice_both_imag_V_last_V_U_vld_out,
        ack_out => imag_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_V_last_V_U_apdone_blk);

    regslice_both_output_r_V_data_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_V_data_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_data_V_U_apdone_blk);

    regslice_both_output_r_V_keep_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_keep_V_U_ack_in_dummy,
        data_out => output_r_TKEEP,
        vld_out => regslice_both_output_r_V_keep_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_keep_V_U_apdone_blk);

    regslice_both_output_r_V_strb_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_strb_V_U_ack_in_dummy,
        data_out => output_r_TSTRB,
        vld_out => regslice_both_output_r_V_strb_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_strb_V_U_apdone_blk);

    regslice_both_output_r_V_last_V_U : component quadrature_demodulator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_216,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_last_V_U_ack_in_dummy,
        data_out => output_r_TLAST,
        vld_out => regslice_both_output_r_V_last_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                diff_imag_V_reg_231 <= diff_imag_V_fu_166_p2;
                diff_real_V_reg_226 <= diff_real_V_fu_160_p2;
                tmp_data_V_1_reg_211 <= real_r_TDATA_int_regslice;
                tmp_data_V_2_reg_221 <= imag_TDATA_int_regslice;
                tmp_last_V_reg_216 <= real_r_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag <= quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1;
                quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1 <= imag_TDATA_int_regslice;
                quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real <= quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1;
                quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1 <= real_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                r_V_1_reg_256 <= grp_fu_178_p2;
                r_V_3_reg_261 <= grp_fu_190_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_output_r_V_data_V_U_apdone_blk, real_r_TVALID_int_regslice, imag_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(real_r_TVALID_int_regslice, imag_TVALID_int_regslice)
    begin
        if (((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_output_r_V_data_V_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_r_TVALID_int_regslice, imag_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(regslice_both_output_r_V_data_V_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    diff_imag_V_fu_166_p0 <= imag_TDATA_int_regslice;
    diff_imag_V_fu_166_p2 <= std_logic_vector(signed(diff_imag_V_fu_166_p0) - signed(quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag));
    diff_real_V_fu_160_p0 <= real_r_TDATA_int_regslice;
    diff_real_V_fu_160_p2 <= std_logic_vector(signed(diff_real_V_fu_160_p0) - signed(quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real));

    imag_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, imag_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            imag_TDATA_blk_n <= imag_TVALID_int_regslice;
        else 
            imag_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imag_TREADY <= regslice_both_imag_V_data_V_U_ack_in;

    imag_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, real_r_TVALID_int_regslice, imag_TVALID_int_regslice)
    begin
        if ((not(((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imag_TREADY_int_regslice <= ap_const_logic_1;
        else 
            imag_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_r_TDATA_int_regslice <= ret_V_fu_196_p2(53 downto 22);
    output_r_TVALID <= regslice_both_output_r_V_data_V_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    real_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, real_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            real_r_TDATA_blk_n <= real_r_TVALID_int_regslice;
        else 
            real_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    real_r_TREADY <= regslice_both_real_r_V_data_V_U_ack_in;

    real_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, real_r_TVALID_int_regslice, imag_TVALID_int_regslice)
    begin
        if ((not(((imag_TVALID_int_regslice = ap_const_logic_0) or (real_r_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            real_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            real_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_fu_196_p2 <= std_logic_vector(unsigned(r_V_1_reg_256) - unsigned(r_V_3_reg_261));
end behav;
