-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity low_pass_filter_first is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of low_pass_filter_first is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "low_pass_filter_first_low_pass_filter_first,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4757,HLS_SYN_LUT=1811,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_FFF0 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110000";
    constant ap_const_lv16_47 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000111";
    constant ap_const_lv16_4E : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001110";
    constant ap_const_lv16_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_const_lv16_FF88 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110001000";
    constant ap_const_lv16_FF53 : STD_LOGIC_VECTOR (15 downto 0) := "1111111101010011";
    constant ap_const_lv16_FFDD : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011101";
    constant ap_const_lv16_DE : STD_LOGIC_VECTOR (15 downto 0) := "0000000011011110";
    constant ap_const_lv16_150 : STD_LOGIC_VECTOR (15 downto 0) := "0000000101010000";
    constant ap_const_lv16_5D : STD_LOGIC_VECTOR (15 downto 0) := "0000000001011101";
    constant ap_const_lv16_FE86 : STD_LOGIC_VECTOR (15 downto 0) := "1111111010000110";
    constant ap_const_lv16_FD9C : STD_LOGIC_VECTOR (15 downto 0) := "1111110110011100";
    constant ap_const_lv16_FF24 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100100100";
    constant ap_const_lv16_263 : STD_LOGIC_VECTOR (15 downto 0) := "0000001001100011";
    constant ap_const_lv16_443 : STD_LOGIC_VECTOR (15 downto 0) := "0000010001000011";
    constant ap_const_lv16_1E3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111100011";
    constant ap_const_lv16_FBFA : STD_LOGIC_VECTOR (15 downto 0) := "1111101111111010";
    constant ap_const_lv16_F7B0 : STD_LOGIC_VECTOR (15 downto 0) := "1111011110110000";
    constant ap_const_lv16_FB4B : STD_LOGIC_VECTOR (15 downto 0) := "1111101101001011";
    constant ap_const_lv16_8C6 : STD_LOGIC_VECTOR (15 downto 0) := "0000100011000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv16_1AE7 : STD_LOGIC_VECTOR (15 downto 0) := "0001101011100111";
    constant ap_const_lv16_27D6 : STD_LOGIC_VECTOR (15 downto 0) := "0010011111010110";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal count_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sum_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln1065_fu_1510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln1065_reg_1949 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_1_reg_1538 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_reg_1543 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_V_reg_1548 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_last_V_reg_1553 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_8_fu_362_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_8_reg_1561 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_542_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_556_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_7_fu_570_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_7_reg_1648 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_fu_584_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_reg_1653 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_fu_598_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_reg_1658 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_fu_612_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_reg_1663 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_fu_626_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_reg_1668 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_640_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_reg_1673 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_fu_654_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_reg_1678 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_932_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_reg_1683 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_946_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_reg_1688 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_960_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_1693 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_6_fu_1010_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_1728 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_1023_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_reg_1733 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_8_fu_1036_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_8_reg_1738 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_fu_1049_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_reg_1743 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_992_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_reg_1748 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_3_reg_1753 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1004_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_1_reg_1758 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_11_fu_1096_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_reg_1783 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_13_fu_1109_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_13_reg_1788 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1078_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_2_reg_1793 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_7_reg_1798 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1090_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_3_reg_1803 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_15_fu_1191_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_15_reg_1828 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_1204_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1833 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1173_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_4_reg_1838 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_12_reg_1843 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1185_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_5_reg_1848 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_19_fu_1286_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_19_reg_1873 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_10_fu_1315_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_10_reg_1878 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_1328_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_21_reg_1883 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1268_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_6_reg_1888 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_16_reg_1893 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1280_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_7_reg_1898 : STD_LOGIC_VECTOR (46 downto 0);
    signal grp_fu_1392_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_8_reg_1923 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_20_reg_1928 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1404_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln1393_9_reg_1933 : STD_LOGIC_VECTOR (46 downto 0);
    signal sum_each_V_reg_1938 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal temp_data_V_fu_1504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_0578652688757800877928101310721160_reg_228 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_1579650690755802875930101110741158_reg_241 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_2580648692753804873932100910761156_reg_254 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_3581646694751806871934100710781154_reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_3573696749808869936100510801152_reg_280 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_2572698747810867938100310821150_reg_293 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_1571700745812865940100110841148_reg_306 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_057070274381486394299910861146_reg_319 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_sum_V_new_0_phi_fu_335_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_V_new_0_reg_332 : STD_LOGIC_VECTOR (31 downto 0);
    signal regslice_both_output_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state10 : BOOLEAN;
    signal ap_block_state10_io : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal add_ln886_fu_1515_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_384_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_980_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal lhs_V_fu_1122_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_fu_1129_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_5_fu_1134_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_1_fu_1144_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_1_fu_1152_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal lhs_V_2_fu_1217_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_2_fu_1224_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_10_fu_1229_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_3_fu_1239_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_3_fu_1247_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal lhs_V_4_fu_1341_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_4_fu_1348_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_14_fu_1353_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_5_fu_1363_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_5_fu_1371_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal lhs_V_6_fu_1410_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_6_fu_1417_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_18_fu_1422_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_7_fu_1432_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_7_fu_1440_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal lhs_V_8_fu_1455_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_8_fu_1462_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_22_fu_1467_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_9_fu_1477_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal ret_V_9_fu_1485_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_input_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_input_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component low_pass_filter_first_mux_42_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component low_pass_filter_first_mux_42_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component low_pass_filter_first_mul_32s_16s_47_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (46 downto 0) );
    end component;


    component low_pass_filter_first_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mux_42_32_1_1_U1 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode,
        din4 => empty_8_fu_362_p2,
        dout => tmp_fu_384_p6);

    mux_42_32_1_1_U2 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1,
        din4 => empty_8_fu_362_p2,
        dout => tmp_1_fu_542_p6);

    mux_42_32_1_1_U3 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2,
        din4 => empty_8_fu_362_p2,
        dout => tmp_2_fu_556_p6);

    mux_42_32_1_1_U4 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3,
        din4 => empty_8_fu_362_p2,
        dout => r_V_7_fu_570_p6);

    mux_42_32_1_1_U5 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4,
        din4 => empty_8_fu_362_p2,
        dout => r_V_6_fu_584_p6);

    mux_42_32_1_1_U6 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5,
        din4 => empty_8_fu_362_p2,
        dout => r_V_5_fu_598_p6);

    mux_42_32_1_1_U7 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6,
        din4 => empty_8_fu_362_p2,
        dout => r_V_4_fu_612_p6);

    mux_42_32_1_1_U8 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7,
        din4 => empty_8_fu_362_p2,
        dout => r_V_3_fu_626_p6);

    mux_42_32_1_1_U9 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9,
        din4 => empty_8_fu_362_p2,
        dout => r_V_2_fu_640_p6);

    mux_42_32_1_1_U10 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10,
        din4 => empty_8_fu_362_p2,
        dout => r_V_1_fu_654_p6);

    mux_42_16_1_1_U11 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FFF0,
        din1 => ap_const_lv16_47,
        din2 => ap_const_lv16_4E,
        din3 => ap_const_lv16_8,
        din4 => empty_8_fu_362_p2,
        dout => tmp_s_fu_932_p6);

    mux_42_16_1_1_U12 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FF88,
        din1 => ap_const_lv16_FF53,
        din2 => ap_const_lv16_FFDD,
        din3 => ap_const_lv16_DE,
        din4 => empty_8_fu_362_p2,
        dout => tmp_9_fu_946_p6);

    mux_42_16_1_1_U13 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_150,
        din1 => ap_const_lv16_5D,
        din2 => ap_const_lv16_FE86,
        din3 => ap_const_lv16_FD9C,
        din4 => empty_8_fu_362_p2,
        dout => tmp_4_fu_960_p6);

    mul_32s_16s_47_2_1_U14 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_data_V_1_reg_1538,
        din1 => tmp_s_reg_1683,
        ce => ap_const_logic_1,
        dout => grp_fu_980_p2);

    mul_32s_16s_47_2_1_U15 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_1_reg_1678,
        din1 => tmp_9_reg_1688,
        ce => ap_const_logic_1,
        dout => grp_fu_992_p2);

    mul_32s_16s_47_2_1_U16 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_2_reg_1673,
        din1 => tmp_4_reg_1693,
        ce => ap_const_logic_1,
        dout => grp_fu_1004_p2);

    mux_42_16_1_1_U17 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FF24,
        din1 => ap_const_lv16_263,
        din2 => ap_const_lv16_443,
        din3 => ap_const_lv16_1E3,
        din4 => empty_8_reg_1561,
        dout => tmp_6_fu_1010_p6);

    mux_42_16_1_1_U18 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FBFA,
        din1 => ap_const_lv16_F7B0,
        din2 => ap_const_lv16_FB4B,
        din3 => ap_const_lv16_8C6,
        din4 => empty_8_reg_1561,
        dout => tmp_8_fu_1023_p6);

    mux_42_32_1_1_U19 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_057070274381486394299910861146_reg_319,
        din1 => mux_case_1571700745812865940100110841148_reg_306,
        din2 => mux_case_2572698747810867938100310821150_reg_293,
        din3 => mux_case_3573696749808869936100510801152_reg_280,
        din4 => empty_8_reg_1561,
        dout => r_V_8_fu_1036_p6);

    mux_42_32_1_1_U20 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_0578652688757800877928101310721160_reg_228,
        din1 => mux_case_1579650690755802875930101110741158_reg_241,
        din2 => mux_case_2580648692753804873932100910761156_reg_254,
        din3 => mux_case_3581646694751806871934100710781154_reg_267,
        din4 => empty_8_reg_1561,
        dout => r_V_9_fu_1049_p6);

    mul_32s_16s_47_2_1_U21 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_3_reg_1668,
        din1 => tmp_6_reg_1728,
        ce => ap_const_logic_1,
        dout => grp_fu_1078_p2);

    mul_32s_16s_47_2_1_U22 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_4_reg_1663,
        din1 => tmp_8_reg_1733,
        ce => ap_const_logic_1,
        dout => grp_fu_1090_p2);

    mux_42_16_1_1_U23 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_1AE7,
        din1 => ap_const_lv16_27D6,
        din2 => ap_const_lv16_27D6,
        din3 => ap_const_lv16_1AE7,
        din4 => empty_8_reg_1561,
        dout => tmp_11_fu_1096_p6);

    mux_42_16_1_1_U24 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_8C6,
        din1 => ap_const_lv16_FB4B,
        din2 => ap_const_lv16_F7B0,
        din3 => ap_const_lv16_FBFA,
        din4 => empty_8_reg_1561,
        dout => tmp_13_fu_1109_p6);

    mul_32s_16s_47_2_1_U25 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_5_reg_1658,
        din1 => tmp_11_reg_1783,
        ce => ap_const_logic_1,
        dout => grp_fu_1173_p2);

    mul_32s_16s_47_2_1_U26 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_6_reg_1653,
        din1 => tmp_13_reg_1788,
        ce => ap_const_logic_1,
        dout => grp_fu_1185_p2);

    mux_42_16_1_1_U27 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_1E3,
        din1 => ap_const_lv16_443,
        din2 => ap_const_lv16_263,
        din3 => ap_const_lv16_FF24,
        din4 => empty_8_reg_1561,
        dout => tmp_15_fu_1191_p6);

    mux_42_16_1_1_U28 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FD9C,
        din1 => ap_const_lv16_FE86,
        din2 => ap_const_lv16_5D,
        din3 => ap_const_lv16_150,
        din4 => empty_8_reg_1561,
        dout => tmp_17_fu_1204_p6);

    mul_32s_16s_47_2_1_U29 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_7_reg_1648,
        din1 => tmp_15_reg_1828,
        ce => ap_const_logic_1,
        dout => grp_fu_1268_p2);

    mul_32s_16s_47_2_1_U30 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_8_reg_1738,
        din1 => tmp_17_reg_1833,
        ce => ap_const_logic_1,
        dout => grp_fu_1280_p2);

    mux_42_16_1_1_U31 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_DE,
        din1 => ap_const_lv16_FFDD,
        din2 => ap_const_lv16_FF53,
        din3 => ap_const_lv16_FF88,
        din4 => empty_8_reg_1561,
        dout => tmp_19_fu_1286_p6);

    mux_42_32_1_1_U32 : component low_pass_filter_first_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41,
        din1 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30,
        din2 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19,
        din3 => p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8,
        din4 => empty_8_reg_1561,
        dout => r_V_10_fu_1315_p6);

    mux_42_16_1_1_U33 : component low_pass_filter_first_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_8,
        din1 => ap_const_lv16_4E,
        din2 => ap_const_lv16_47,
        din3 => ap_const_lv16_FFF0,
        din4 => empty_8_reg_1561,
        dout => tmp_21_fu_1328_p6);

    mul_32s_16s_47_2_1_U34 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_9_reg_1743,
        din1 => tmp_19_reg_1873,
        ce => ap_const_logic_1,
        dout => grp_fu_1392_p2);

    mul_32s_16s_47_2_1_U35 : component low_pass_filter_first_mul_32s_16s_47_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 47)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => r_V_10_reg_1878,
        din1 => tmp_21_reg_1883,
        ce => ap_const_logic_1,
        dout => grp_fu_1404_p2);

    regslice_both_input_r_V_data_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_data_V_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_data_V_U_apdone_blk);

    regslice_both_input_r_V_keep_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TKEEP,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_keep_V_U_ack_in,
        data_out => input_r_TKEEP_int_regslice,
        vld_out => regslice_both_input_r_V_keep_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_keep_V_U_apdone_blk);

    regslice_both_input_r_V_strb_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TSTRB,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_strb_V_U_ack_in,
        data_out => input_r_TSTRB_int_regslice,
        vld_out => regslice_both_input_r_V_strb_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_strb_V_U_apdone_blk);

    regslice_both_input_r_V_last_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TLAST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_last_V_U_ack_in,
        data_out => input_r_TLAST_int_regslice,
        vld_out => regslice_both_input_r_V_last_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_last_V_U_apdone_blk);

    regslice_both_output_r_V_data_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_V_data_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_data_V_U_apdone_blk);

    regslice_both_output_r_V_keep_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_V_reg_1543,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_keep_V_U_ack_in_dummy,
        data_out => output_r_TKEEP,
        vld_out => regslice_both_output_r_V_keep_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_keep_V_U_apdone_blk);

    regslice_both_output_r_V_strb_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_V_reg_1548,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_strb_V_U_ack_in_dummy,
        data_out => output_r_TSTRB,
        vld_out => regslice_both_output_r_V_strb_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_strb_V_U_apdone_blk);

    regslice_both_output_r_V_last_V_U : component low_pass_filter_first_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_1553,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_last_V_U_ack_in_dummy,
        data_out => output_r_TLAST,
        vld_out => regslice_both_output_r_V_last_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    count_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1)))) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                count_V <= add_ln886_fu_1515_p2;
            elsif ((not(((ap_const_boolean_1 = ap_block_state10_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln1065_reg_1949 = ap_const_lv1_1))) then 
                count_V <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    mux_case_057070274381486394299910861146_reg_319_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0))) then 
                mux_case_057070274381486394299910861146_reg_319 <= tmp_2_fu_556_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_057070274381486394299910861146_reg_319 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34;
            end if; 
        end if;
    end process;

    mux_case_0578652688757800877928101310721160_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0))) then 
                mux_case_0578652688757800877928101310721160_reg_228 <= tmp_1_fu_542_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_0578652688757800877928101310721160_reg_228 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33;
            end if; 
        end if;
    end process;

    mux_case_1571700745812865940100110841148_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1))) then 
                mux_case_1571700745812865940100110841148_reg_306 <= tmp_2_fu_556_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_1571700745812865940100110841148_reg_306 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23;
            end if; 
        end if;
    end process;

    mux_case_1579650690755802875930101110741158_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1))) then 
                mux_case_1579650690755802875930101110741158_reg_241 <= tmp_1_fu_542_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_1579650690755802875930101110741158_reg_241 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22;
            end if; 
        end if;
    end process;

    mux_case_2572698747810867938100310821150_reg_293_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2))) then 
                mux_case_2572698747810867938100310821150_reg_293 <= tmp_2_fu_556_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_2572698747810867938100310821150_reg_293 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12;
            end if; 
        end if;
    end process;

    mux_case_2580648692753804873932100910761156_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2))) then 
                mux_case_2580648692753804873932100910761156_reg_254 <= tmp_1_fu_542_p6;
            elsif ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3)))) then 
                mux_case_2580648692753804873932100910761156_reg_254 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11;
            end if; 
        end if;
    end process;

    mux_case_3573696749808869936100510801152_reg_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)))) then 
                mux_case_3573696749808869936100510801152_reg_280 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1;
            elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3))) then 
                mux_case_3573696749808869936100510801152_reg_280 <= tmp_2_fu_556_p6;
            end if; 
        end if;
    end process;

    mux_case_3581646694751806871934100710781154_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1)) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2)))) then 
                mux_case_3581646694751806871934100710781154_reg_267 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode;
            elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3))) then 
                mux_case_3581646694751806871934100710781154_reg_267 <= tmp_1_fu_542_p6;
            end if; 
        end if;
    end process;

    sum_V_new_0_reg_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1)))) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_V_new_0_reg_332 <= temp_data_V_fu_1504_p2;
            elsif ((not(((ap_const_boolean_1 = ap_block_state10_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln1065_reg_1949 = ap_const_lv1_1))) then 
                sum_V_new_0_reg_332 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_8_reg_1561 <= empty_8_fu_362_p2;
                r_V_1_reg_1678 <= r_V_1_fu_654_p6;
                r_V_2_reg_1673 <= r_V_2_fu_640_p6;
                r_V_3_reg_1668 <= r_V_3_fu_626_p6;
                r_V_4_reg_1663 <= r_V_4_fu_612_p6;
                r_V_5_reg_1658 <= r_V_5_fu_598_p6;
                r_V_6_reg_1653 <= r_V_6_fu_584_p6;
                r_V_7_reg_1648 <= r_V_7_fu_570_p6;
                tmp_4_reg_1693 <= tmp_4_fu_960_p6;
                tmp_9_reg_1688 <= tmp_9_fu_946_p6;
                tmp_data_V_1_reg_1538 <= input_r_TDATA_int_regslice;
                tmp_keep_V_reg_1543 <= input_r_TKEEP_int_regslice;
                tmp_last_V_reg_1553 <= input_r_TLAST_int_regslice;
                tmp_s_reg_1683 <= tmp_s_fu_932_p6;
                tmp_strb_V_reg_1548 <= input_r_TSTRB_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln1065_reg_1949 <= icmp_ln1065_fu_1510_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln1393_1_reg_1758 <= grp_fu_1004_p2;
                mul_ln1393_reg_1748 <= grp_fu_992_p2;
                tmp_11_reg_1783 <= tmp_11_fu_1096_p6;
                tmp_13_reg_1788 <= tmp_13_fu_1109_p6;
                tmp_3_reg_1753 <= grp_fu_980_p2(46 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                mul_ln1393_2_reg_1793 <= grp_fu_1078_p2;
                mul_ln1393_3_reg_1803 <= grp_fu_1090_p2;
                tmp_15_reg_1828 <= tmp_15_fu_1191_p6;
                tmp_17_reg_1833 <= tmp_17_fu_1204_p6;
                tmp_7_reg_1798 <= ret_V_1_fu_1152_p2(46 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                mul_ln1393_4_reg_1838 <= grp_fu_1173_p2;
                mul_ln1393_5_reg_1848 <= grp_fu_1185_p2;
                r_V_10_reg_1878 <= r_V_10_fu_1315_p6;
                tmp_12_reg_1843 <= ret_V_3_fu_1247_p2(46 downto 15);
                tmp_19_reg_1873 <= tmp_19_fu_1286_p6;
                tmp_21_reg_1883 <= tmp_21_fu_1328_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                mul_ln1393_6_reg_1888 <= grp_fu_1268_p2;
                mul_ln1393_7_reg_1898 <= grp_fu_1280_p2;
                tmp_16_reg_1893 <= ret_V_5_fu_1371_p2(46 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                mul_ln1393_8_reg_1923 <= grp_fu_1392_p2;
                mul_ln1393_9_reg_1933 <= grp_fu_1404_p2;
                tmp_20_reg_1928 <= ret_V_7_fu_1440_p2(46 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_3))) then
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode <= tmp_1_fu_542_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1 <= tmp_2_fu_556_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10 <= input_r_TDATA_int_regslice;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2 <= r_V_7_fu_570_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3 <= r_V_6_fu_584_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4 <= r_V_5_fu_598_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5 <= r_V_4_fu_612_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6 <= r_V_3_fu_626_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7 <= r_V_2_fu_640_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8 <= tmp_fu_384_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9 <= r_V_1_fu_654_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_2))) then
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11 <= tmp_1_fu_542_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12 <= tmp_2_fu_556_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13 <= r_V_7_fu_570_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14 <= r_V_6_fu_584_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15 <= r_V_5_fu_598_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16 <= r_V_4_fu_612_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17 <= r_V_3_fu_626_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18 <= r_V_2_fu_640_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19 <= tmp_fu_384_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20 <= r_V_1_fu_654_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_1))) then
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22 <= tmp_1_fu_542_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23 <= tmp_2_fu_556_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24 <= r_V_7_fu_570_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25 <= r_V_6_fu_584_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26 <= r_V_5_fu_598_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27 <= r_V_4_fu_612_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28 <= r_V_3_fu_626_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29 <= r_V_2_fu_640_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30 <= tmp_fu_384_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31 <= r_V_1_fu_654_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_8_fu_362_p2 = ap_const_lv2_0))) then
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33 <= tmp_1_fu_542_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34 <= tmp_2_fu_556_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35 <= r_V_7_fu_570_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36 <= r_V_6_fu_584_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37 <= r_V_5_fu_598_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38 <= r_V_4_fu_612_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39 <= r_V_3_fu_626_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40 <= r_V_2_fu_640_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41 <= tmp_fu_384_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42 <= r_V_1_fu_654_p6;
                p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_V_8_reg_1738 <= r_V_8_fu_1036_p6;
                r_V_9_reg_1743 <= r_V_9_fu_1049_p6;
                tmp_6_reg_1728 <= tmp_6_fu_1010_p6;
                tmp_8_reg_1733 <= tmp_8_fu_1023_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state10_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                sum_V <= ap_phi_mux_sum_V_new_0_phi_fu_335_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                sum_each_V_reg_1938 <= ret_V_9_fu_1485_p2(46 downto 15);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state9, icmp_ln1065_fu_1510_p2, ap_CS_fsm_state10, icmp_ln1065_reg_1949, regslice_both_output_r_V_data_V_U_apdone_blk, ap_block_state10_io, ap_block_state9_io, input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if ((not(((ap_const_boolean_1 = ap_block_state10_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln886_fu_1515_p2 <= std_logic_vector(unsigned(count_V) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(icmp_ln1065_reg_1949, regslice_both_output_r_V_data_V_U_apdone_blk, ap_block_state10_io, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state10_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(input_r_TVALID_int_regslice)
    begin
        if ((input_r_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(icmp_ln1065_fu_1510_p2, ap_block_state9_io, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state10_assign_proc : process(icmp_ln1065_reg_1949, regslice_both_output_r_V_data_V_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state10 <= ((regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)));
    end process;


    ap_block_state10_io_assign_proc : process(icmp_ln1065_reg_1949, output_r_TREADY_int_regslice)
    begin
                ap_block_state10_io <= ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_reg_1949 = ap_const_lv1_1));
    end process;


    ap_block_state9_assign_proc : process(icmp_ln1065_fu_1510_p2, output_r_TREADY_int_regslice)
    begin
                ap_block_state9 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1));
    end process;


    ap_block_state9_io_assign_proc : process(icmp_ln1065_fu_1510_p2, output_r_TREADY_int_regslice)
    begin
                ap_block_state9_io <= ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1));
    end process;


    ap_phi_mux_sum_V_new_0_phi_fu_335_p4_assign_proc : process(ap_CS_fsm_state10, icmp_ln1065_reg_1949, sum_V_new_0_reg_332)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln1065_reg_1949 = ap_const_lv1_1))) then 
            ap_phi_mux_sum_V_new_0_phi_fu_335_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_sum_V_new_0_phi_fu_335_p4 <= sum_V_new_0_reg_332;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_8_fu_362_p2 <= (count_V xor ap_const_lv2_3);
    icmp_ln1065_fu_1510_p2 <= "1" when (count_V = ap_const_lv2_3) else "0";

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_V_data_V_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lhs_V_1_fu_1144_p3 <= (tmp_5_fu_1134_p4 & ap_const_lv15_0);
    lhs_V_2_fu_1217_p3 <= (tmp_7_reg_1798 & ap_const_lv15_0);
    lhs_V_3_fu_1239_p3 <= (tmp_10_fu_1229_p4 & ap_const_lv15_0);
    lhs_V_4_fu_1341_p3 <= (tmp_12_reg_1843 & ap_const_lv15_0);
    lhs_V_5_fu_1363_p3 <= (tmp_14_fu_1353_p4 & ap_const_lv15_0);
    lhs_V_6_fu_1410_p3 <= (tmp_16_reg_1893 & ap_const_lv15_0);
    lhs_V_7_fu_1432_p3 <= (tmp_18_fu_1422_p4 & ap_const_lv15_0);
    lhs_V_8_fu_1455_p3 <= (tmp_20_reg_1928 & ap_const_lv15_0);
    lhs_V_9_fu_1477_p3 <= (tmp_22_fu_1467_p4 & ap_const_lv15_0);
    lhs_V_fu_1122_p3 <= (tmp_3_reg_1753 & ap_const_lv15_0);

    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state9, icmp_ln1065_fu_1510_p2, ap_CS_fsm_state10, icmp_ln1065_reg_1949, output_r_TREADY_int_regslice)
    begin
        if ((((icmp_ln1065_fu_1510_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln1065_reg_1949 = ap_const_lv1_1)))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_r_TDATA_int_regslice <= std_logic_vector(unsigned(sum_V) + unsigned(sum_each_V_reg_1938));
    output_r_TVALID <= regslice_both_output_r_V_data_V_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state9, icmp_ln1065_fu_1510_p2, ap_block_state9_io, output_r_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1)))) and (icmp_ln1065_fu_1510_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_1_fu_1152_p2 <= std_logic_vector(unsigned(lhs_V_1_fu_1144_p3) + unsigned(mul_ln1393_1_reg_1758));
    ret_V_2_fu_1224_p2 <= std_logic_vector(unsigned(lhs_V_2_fu_1217_p3) + unsigned(mul_ln1393_2_reg_1793));
    ret_V_3_fu_1247_p2 <= std_logic_vector(unsigned(lhs_V_3_fu_1239_p3) + unsigned(mul_ln1393_3_reg_1803));
    ret_V_4_fu_1348_p2 <= std_logic_vector(unsigned(lhs_V_4_fu_1341_p3) + unsigned(mul_ln1393_4_reg_1838));
    ret_V_5_fu_1371_p2 <= std_logic_vector(unsigned(lhs_V_5_fu_1363_p3) + unsigned(mul_ln1393_5_reg_1848));
    ret_V_6_fu_1417_p2 <= std_logic_vector(unsigned(lhs_V_6_fu_1410_p3) + unsigned(mul_ln1393_6_reg_1888));
    ret_V_7_fu_1440_p2 <= std_logic_vector(unsigned(lhs_V_7_fu_1432_p3) + unsigned(mul_ln1393_7_reg_1898));
    ret_V_8_fu_1462_p2 <= std_logic_vector(unsigned(lhs_V_8_fu_1455_p3) + unsigned(mul_ln1393_8_reg_1923));
    ret_V_9_fu_1485_p2 <= std_logic_vector(unsigned(lhs_V_9_fu_1477_p3) + unsigned(mul_ln1393_9_reg_1933));
    ret_V_fu_1129_p2 <= std_logic_vector(unsigned(lhs_V_fu_1122_p3) + unsigned(mul_ln1393_reg_1748));
    temp_data_V_fu_1504_p2 <= std_logic_vector(unsigned(sum_V) + unsigned(sum_each_V_reg_1938));
    tmp_10_fu_1229_p4 <= ret_V_2_fu_1224_p2(46 downto 15);
    tmp_14_fu_1353_p4 <= ret_V_4_fu_1348_p2(46 downto 15);
    tmp_18_fu_1422_p4 <= ret_V_6_fu_1417_p2(46 downto 15);
    tmp_22_fu_1467_p4 <= ret_V_8_fu_1462_p2(46 downto 15);
    tmp_5_fu_1134_p4 <= ret_V_fu_1129_p2(46 downto 15);
end behav;
