# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/quadrature_demodulator/quadrature_demodulator/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/quadrature_demodulator/quadrature_demodulator/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/quadrature_demodulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/quadrature_demodulator/quadrature_demodulator/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/quadrature_demodulator/quadrature_demodulator/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/quadrature_demodulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
