# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/low_pass_filter_second/low_pass_filter_second/solution1/impl/verilog/low_pass_filter_second.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: d:/xilinx/SDR/PYNQ_Z2_FM_Radio-main/hls/low_pass_filter_second/low_pass_filter_second/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
