// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="low_pass_filter_first_low_pass_filter_first,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4757,HLS_SYN_LUT=1811,HLS_VERSION=2022_1}" *)

module low_pass_filter_first (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [3:0] input_r_TKEEP;
input  [3:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [31:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [3:0] output_r_TKEEP;
output  [3:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [1:0] count_V;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19;
reg   [31:0] p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8;
reg   [31:0] sum_V;
reg    input_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln1065_fu_1510_p2;
wire    ap_CS_fsm_state10;
reg   [0:0] icmp_ln1065_reg_1949;
reg  signed [31:0] tmp_data_V_1_reg_1538;
reg   [3:0] tmp_keep_V_reg_1543;
reg   [3:0] tmp_strb_V_reg_1548;
reg   [0:0] tmp_last_V_reg_1553;
wire   [1:0] empty_8_fu_362_p2;
reg   [1:0] empty_8_reg_1561;
wire   [31:0] tmp_1_fu_542_p6;
wire   [31:0] tmp_2_fu_556_p6;
wire  signed [31:0] r_V_7_fu_570_p6;
reg  signed [31:0] r_V_7_reg_1648;
wire  signed [31:0] r_V_6_fu_584_p6;
reg  signed [31:0] r_V_6_reg_1653;
wire  signed [31:0] r_V_5_fu_598_p6;
reg  signed [31:0] r_V_5_reg_1658;
wire  signed [31:0] r_V_4_fu_612_p6;
reg  signed [31:0] r_V_4_reg_1663;
wire  signed [31:0] r_V_3_fu_626_p6;
reg  signed [31:0] r_V_3_reg_1668;
wire  signed [31:0] r_V_2_fu_640_p6;
reg  signed [31:0] r_V_2_reg_1673;
wire  signed [31:0] r_V_1_fu_654_p6;
reg  signed [31:0] r_V_1_reg_1678;
wire   [15:0] tmp_s_fu_932_p6;
reg  signed [15:0] tmp_s_reg_1683;
wire   [15:0] tmp_9_fu_946_p6;
reg  signed [15:0] tmp_9_reg_1688;
wire   [15:0] tmp_4_fu_960_p6;
reg  signed [15:0] tmp_4_reg_1693;
wire    ap_CS_fsm_state2;
wire   [15:0] tmp_6_fu_1010_p6;
reg  signed [15:0] tmp_6_reg_1728;
wire   [15:0] tmp_8_fu_1023_p6;
reg  signed [15:0] tmp_8_reg_1733;
wire   [31:0] r_V_8_fu_1036_p6;
reg  signed [31:0] r_V_8_reg_1738;
wire   [31:0] r_V_9_fu_1049_p6;
reg  signed [31:0] r_V_9_reg_1743;
wire   [46:0] grp_fu_992_p2;
reg   [46:0] mul_ln1393_reg_1748;
wire    ap_CS_fsm_state3;
reg   [31:0] tmp_3_reg_1753;
wire   [46:0] grp_fu_1004_p2;
reg   [46:0] mul_ln1393_1_reg_1758;
wire   [15:0] tmp_11_fu_1096_p6;
reg  signed [15:0] tmp_11_reg_1783;
wire   [15:0] tmp_13_fu_1109_p6;
reg  signed [15:0] tmp_13_reg_1788;
wire   [46:0] grp_fu_1078_p2;
reg   [46:0] mul_ln1393_2_reg_1793;
wire    ap_CS_fsm_state4;
reg   [31:0] tmp_7_reg_1798;
wire   [46:0] grp_fu_1090_p2;
reg   [46:0] mul_ln1393_3_reg_1803;
wire   [15:0] tmp_15_fu_1191_p6;
reg  signed [15:0] tmp_15_reg_1828;
wire   [15:0] tmp_17_fu_1204_p6;
reg  signed [15:0] tmp_17_reg_1833;
wire   [46:0] grp_fu_1173_p2;
reg   [46:0] mul_ln1393_4_reg_1838;
wire    ap_CS_fsm_state5;
reg   [31:0] tmp_12_reg_1843;
wire   [46:0] grp_fu_1185_p2;
reg   [46:0] mul_ln1393_5_reg_1848;
wire   [15:0] tmp_19_fu_1286_p6;
reg  signed [15:0] tmp_19_reg_1873;
wire   [31:0] r_V_10_fu_1315_p6;
reg  signed [31:0] r_V_10_reg_1878;
wire   [15:0] tmp_21_fu_1328_p6;
reg  signed [15:0] tmp_21_reg_1883;
wire   [46:0] grp_fu_1268_p2;
reg   [46:0] mul_ln1393_6_reg_1888;
wire    ap_CS_fsm_state6;
reg   [31:0] tmp_16_reg_1893;
wire   [46:0] grp_fu_1280_p2;
reg   [46:0] mul_ln1393_7_reg_1898;
wire   [46:0] grp_fu_1392_p2;
reg   [46:0] mul_ln1393_8_reg_1923;
wire    ap_CS_fsm_state7;
reg   [31:0] tmp_20_reg_1928;
wire   [46:0] grp_fu_1404_p2;
reg   [46:0] mul_ln1393_9_reg_1933;
reg   [31:0] sum_each_V_reg_1938;
wire    ap_CS_fsm_state8;
wire   [31:0] temp_data_V_fu_1504_p2;
reg   [31:0] mux_case_0578652688757800877928101310721160_reg_228;
reg   [31:0] mux_case_1579650690755802875930101110741158_reg_241;
reg   [31:0] mux_case_2580648692753804873932100910761156_reg_254;
reg   [31:0] mux_case_3581646694751806871934100710781154_reg_267;
reg   [31:0] mux_case_3573696749808869936100510801152_reg_280;
reg   [31:0] mux_case_2572698747810867938100310821150_reg_293;
reg   [31:0] mux_case_1571700745812865940100110841148_reg_306;
reg   [31:0] mux_case_057070274381486394299910861146_reg_319;
reg   [31:0] ap_phi_mux_sum_V_new_0_phi_fu_335_p4;
reg   [31:0] sum_V_new_0_reg_332;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
reg    ap_block_state10;
reg    ap_block_state10_io;
reg    ap_block_state9;
reg    ap_block_state9_io;
wire   [1:0] add_ln886_fu_1515_p2;
wire   [31:0] tmp_fu_384_p6;
wire   [46:0] grp_fu_980_p2;
wire   [46:0] lhs_V_fu_1122_p3;
wire   [46:0] ret_V_fu_1129_p2;
wire   [31:0] tmp_5_fu_1134_p4;
wire   [46:0] lhs_V_1_fu_1144_p3;
wire   [46:0] ret_V_1_fu_1152_p2;
wire   [46:0] lhs_V_2_fu_1217_p3;
wire   [46:0] ret_V_2_fu_1224_p2;
wire   [31:0] tmp_10_fu_1229_p4;
wire   [46:0] lhs_V_3_fu_1239_p3;
wire   [46:0] ret_V_3_fu_1247_p2;
wire   [46:0] lhs_V_4_fu_1341_p3;
wire   [46:0] ret_V_4_fu_1348_p2;
wire   [31:0] tmp_14_fu_1353_p4;
wire   [46:0] lhs_V_5_fu_1363_p3;
wire   [46:0] ret_V_5_fu_1371_p2;
wire   [46:0] lhs_V_6_fu_1410_p3;
wire   [46:0] ret_V_6_fu_1417_p2;
wire   [31:0] tmp_18_fu_1422_p4;
wire   [46:0] lhs_V_7_fu_1432_p3;
wire   [46:0] ret_V_7_fu_1440_p2;
wire   [46:0] lhs_V_8_fu_1455_p3;
wire   [46:0] ret_V_8_fu_1462_p2;
wire   [31:0] tmp_22_fu_1467_p4;
wire   [46:0] lhs_V_9_fu_1477_p3;
wire   [46:0] ret_V_9_fu_1485_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire   [31:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [3:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [3:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire   [31:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 count_V = 2'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19 = 32'd0;
#0 p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8 = 32'd0;
#0 sum_V = 32'd0;
#0 ap_CS_fsm = 10'd1;
end

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U1(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_fu_384_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U2(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_1_fu_542_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U3(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_2_fu_556_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U4(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_7_fu_570_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U5(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_6_fu_584_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U6(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_5_fu_598_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U7(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_4_fu_612_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U8(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_3_fu_626_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U9(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_2_fu_640_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U10(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10),
    .din4(empty_8_fu_362_p2),
    .dout(r_V_1_fu_654_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U11(
    .din0(16'd65520),
    .din1(16'd71),
    .din2(16'd78),
    .din3(16'd8),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_s_fu_932_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U12(
    .din0(16'd65416),
    .din1(16'd65363),
    .din2(16'd65501),
    .din3(16'd222),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_9_fu_946_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U13(
    .din0(16'd336),
    .din1(16'd93),
    .din2(16'd65158),
    .din3(16'd64924),
    .din4(empty_8_fu_362_p2),
    .dout(tmp_4_fu_960_p6)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_data_V_1_reg_1538),
    .din1(tmp_s_reg_1683),
    .ce(1'b1),
    .dout(grp_fu_980_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_1_reg_1678),
    .din1(tmp_9_reg_1688),
    .ce(1'b1),
    .dout(grp_fu_992_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_2_reg_1673),
    .din1(tmp_4_reg_1693),
    .ce(1'b1),
    .dout(grp_fu_1004_p2)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U17(
    .din0(16'd65316),
    .din1(16'd611),
    .din2(16'd1091),
    .din3(16'd483),
    .din4(empty_8_reg_1561),
    .dout(tmp_6_fu_1010_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U18(
    .din0(16'd64506),
    .din1(16'd63408),
    .din2(16'd64331),
    .din3(16'd2246),
    .din4(empty_8_reg_1561),
    .dout(tmp_8_fu_1023_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U19(
    .din0(mux_case_057070274381486394299910861146_reg_319),
    .din1(mux_case_1571700745812865940100110841148_reg_306),
    .din2(mux_case_2572698747810867938100310821150_reg_293),
    .din3(mux_case_3573696749808869936100510801152_reg_280),
    .din4(empty_8_reg_1561),
    .dout(r_V_8_fu_1036_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U20(
    .din0(mux_case_0578652688757800877928101310721160_reg_228),
    .din1(mux_case_1579650690755802875930101110741158_reg_241),
    .din2(mux_case_2580648692753804873932100910761156_reg_254),
    .din3(mux_case_3581646694751806871934100710781154_reg_267),
    .din4(empty_8_reg_1561),
    .dout(r_V_9_fu_1049_p6)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U21(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_3_reg_1668),
    .din1(tmp_6_reg_1728),
    .ce(1'b1),
    .dout(grp_fu_1078_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U22(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_4_reg_1663),
    .din1(tmp_8_reg_1733),
    .ce(1'b1),
    .dout(grp_fu_1090_p2)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U23(
    .din0(16'd6887),
    .din1(16'd10198),
    .din2(16'd10198),
    .din3(16'd6887),
    .din4(empty_8_reg_1561),
    .dout(tmp_11_fu_1096_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U24(
    .din0(16'd2246),
    .din1(16'd64331),
    .din2(16'd63408),
    .din3(16'd64506),
    .din4(empty_8_reg_1561),
    .dout(tmp_13_fu_1109_p6)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U25(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_5_reg_1658),
    .din1(tmp_11_reg_1783),
    .ce(1'b1),
    .dout(grp_fu_1173_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_6_reg_1653),
    .din1(tmp_13_reg_1788),
    .ce(1'b1),
    .dout(grp_fu_1185_p2)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U27(
    .din0(16'd483),
    .din1(16'd1091),
    .din2(16'd611),
    .din3(16'd65316),
    .din4(empty_8_reg_1561),
    .dout(tmp_15_fu_1191_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U28(
    .din0(16'd64924),
    .din1(16'd65158),
    .din2(16'd93),
    .din3(16'd336),
    .din4(empty_8_reg_1561),
    .dout(tmp_17_fu_1204_p6)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U29(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_7_reg_1648),
    .din1(tmp_15_reg_1828),
    .ce(1'b1),
    .dout(grp_fu_1268_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_8_reg_1738),
    .din1(tmp_17_reg_1833),
    .ce(1'b1),
    .dout(grp_fu_1280_p2)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U31(
    .din0(16'd222),
    .din1(16'd65501),
    .din2(16'd65363),
    .din3(16'd65416),
    .din4(empty_8_reg_1561),
    .dout(tmp_19_fu_1286_p6)
);

low_pass_filter_first_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U32(
    .din0(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41),
    .din1(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30),
    .din2(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19),
    .din3(p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8),
    .din4(empty_8_reg_1561),
    .dout(r_V_10_fu_1315_p6)
);

low_pass_filter_first_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U33(
    .din0(16'd8),
    .din1(16'd78),
    .din2(16'd71),
    .din3(16'd65520),
    .din4(empty_8_reg_1561),
    .dout(tmp_21_fu_1328_p6)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_9_reg_1743),
    .din1(tmp_19_reg_1873),
    .ce(1'b1),
    .dout(grp_fu_1392_p2)
);

low_pass_filter_first_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_10_reg_1878),
    .din1(tmp_21_reg_1883),
    .ce(1'b1),
    .dout(grp_fu_1404_p2)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_reg_1543),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_reg_1548),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

low_pass_filter_first_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_1553),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state9_io) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1))) & (icmp_ln1065_fu_1510_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        count_V <= add_ln886_fu_1515_p2;
    end else if ((~((1'b1 == ap_block_state10_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1))) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln1065_reg_1949 == 1'd1))) begin
        count_V <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0))) begin
        mux_case_057070274381486394299910861146_reg_319 <= tmp_2_fu_556_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_057070274381486394299910861146_reg_319 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0))) begin
        mux_case_0578652688757800877928101310721160_reg_228 <= tmp_1_fu_542_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_0578652688757800877928101310721160_reg_228 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1))) begin
        mux_case_1571700745812865940100110841148_reg_306 <= tmp_2_fu_556_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_1571700745812865940100110841148_reg_306 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1))) begin
        mux_case_1579650690755802875930101110741158_reg_241 <= tmp_1_fu_542_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_1579650690755802875930101110741158_reg_241 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2))) begin
        mux_case_2572698747810867938100310821150_reg_293 <= tmp_2_fu_556_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_2572698747810867938100310821150_reg_293 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2))) begin
        mux_case_2580648692753804873932100910761156_reg_254 <= tmp_1_fu_542_p6;
    end else if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3)))) begin
        mux_case_2580648692753804873932100910761156_reg_254 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11;
    end
end

always @ (posedge ap_clk) begin
    if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)))) begin
        mux_case_3573696749808869936100510801152_reg_280 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1;
    end else if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3))) begin
        mux_case_3573696749808869936100510801152_reg_280 <= tmp_2_fu_556_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1)) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2)))) begin
        mux_case_3581646694751806871934100710781154_reg_267 <= p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode;
    end else if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3))) begin
        mux_case_3581646694751806871934100710781154_reg_267 <= tmp_1_fu_542_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state9_io) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1))) & (icmp_ln1065_fu_1510_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        sum_V_new_0_reg_332 <= temp_data_V_fu_1504_p2;
    end else if ((~((1'b1 == ap_block_state10_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1))) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln1065_reg_1949 == 1'd1))) begin
        sum_V_new_0_reg_332 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_8_reg_1561 <= empty_8_fu_362_p2;
        r_V_1_reg_1678 <= r_V_1_fu_654_p6;
        r_V_2_reg_1673 <= r_V_2_fu_640_p6;
        r_V_3_reg_1668 <= r_V_3_fu_626_p6;
        r_V_4_reg_1663 <= r_V_4_fu_612_p6;
        r_V_5_reg_1658 <= r_V_5_fu_598_p6;
        r_V_6_reg_1653 <= r_V_6_fu_584_p6;
        r_V_7_reg_1648 <= r_V_7_fu_570_p6;
        tmp_4_reg_1693 <= tmp_4_fu_960_p6;
        tmp_9_reg_1688 <= tmp_9_fu_946_p6;
        tmp_data_V_1_reg_1538 <= input_r_TDATA_int_regslice;
        tmp_keep_V_reg_1543 <= input_r_TKEEP_int_regslice;
        tmp_last_V_reg_1553 <= input_r_TLAST_int_regslice;
        tmp_s_reg_1683 <= tmp_s_fu_932_p6;
        tmp_strb_V_reg_1548 <= input_r_TSTRB_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln1065_reg_1949 <= icmp_ln1065_fu_1510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln1393_1_reg_1758 <= grp_fu_1004_p2;
        mul_ln1393_reg_1748 <= grp_fu_992_p2;
        tmp_11_reg_1783 <= tmp_11_fu_1096_p6;
        tmp_13_reg_1788 <= tmp_13_fu_1109_p6;
        tmp_3_reg_1753 <= {{grp_fu_980_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln1393_2_reg_1793 <= grp_fu_1078_p2;
        mul_ln1393_3_reg_1803 <= grp_fu_1090_p2;
        tmp_15_reg_1828 <= tmp_15_fu_1191_p6;
        tmp_17_reg_1833 <= tmp_17_fu_1204_p6;
        tmp_7_reg_1798 <= {{ret_V_1_fu_1152_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln1393_4_reg_1838 <= grp_fu_1173_p2;
        mul_ln1393_5_reg_1848 <= grp_fu_1185_p2;
        r_V_10_reg_1878 <= r_V_10_fu_1315_p6;
        tmp_12_reg_1843 <= {{ret_V_3_fu_1247_p2[46:15]}};
        tmp_19_reg_1873 <= tmp_19_fu_1286_p6;
        tmp_21_reg_1883 <= tmp_21_fu_1328_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln1393_6_reg_1888 <= grp_fu_1268_p2;
        mul_ln1393_7_reg_1898 <= grp_fu_1280_p2;
        tmp_16_reg_1893 <= {{ret_V_5_fu_1371_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mul_ln1393_8_reg_1923 <= grp_fu_1392_p2;
        mul_ln1393_9_reg_1933 <= grp_fu_1404_p2;
        tmp_20_reg_1928 <= {{ret_V_7_fu_1440_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd3))) begin
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode <= tmp_1_fu_542_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_1 <= tmp_2_fu_556_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_10 <= input_r_TDATA_int_regslice;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_2 <= r_V_7_fu_570_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_3 <= r_V_6_fu_584_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_4 <= r_V_5_fu_598_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_5 <= r_V_4_fu_612_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_6 <= r_V_3_fu_626_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_7 <= r_V_2_fu_640_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_8 <= tmp_fu_384_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_9 <= r_V_1_fu_654_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd2))) begin
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_11 <= tmp_1_fu_542_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_12 <= tmp_2_fu_556_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_13 <= r_V_7_fu_570_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_14 <= r_V_6_fu_584_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_15 <= r_V_5_fu_598_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_16 <= r_V_4_fu_612_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_17 <= r_V_3_fu_626_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_18 <= r_V_2_fu_640_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_19 <= tmp_fu_384_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_20 <= r_V_1_fu_654_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_21 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd1))) begin
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_22 <= tmp_1_fu_542_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_23 <= tmp_2_fu_556_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_24 <= r_V_7_fu_570_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_25 <= r_V_6_fu_584_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_26 <= r_V_5_fu_598_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_27 <= r_V_4_fu_612_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_28 <= r_V_3_fu_626_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_29 <= r_V_2_fu_640_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_30 <= tmp_fu_384_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_31 <= r_V_1_fu_654_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_32 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (empty_8_fu_362_p2 == 2'd0))) begin
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_33 <= tmp_1_fu_542_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_34 <= tmp_2_fu_556_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_35 <= r_V_7_fu_570_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_36 <= r_V_6_fu_584_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_37 <= r_V_5_fu_598_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_38 <= r_V_4_fu_612_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_39 <= r_V_3_fu_626_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_40 <= r_V_2_fu_640_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_41 <= tmp_fu_384_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_42 <= r_V_1_fu_654_p6;
        p_ZZ21low_pass_filter_firstRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mode_43 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_8_reg_1738 <= r_V_8_fu_1036_p6;
        r_V_9_reg_1743 <= r_V_9_fu_1049_p6;
        tmp_6_reg_1728 <= tmp_6_fu_1010_p6;
        tmp_8_reg_1733 <= tmp_8_fu_1023_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state10_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1))) & (1'b1 == ap_CS_fsm_state10))) begin
        sum_V <= ap_phi_mux_sum_V_new_0_phi_fu_335_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sum_each_V_reg_1938 <= {{ret_V_9_fu_1485_p2[46:15]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state10_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1)))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_r_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state9_io) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1)))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln1065_reg_1949 == 1'd1))) begin
        ap_phi_mux_sum_V_new_0_phi_fu_335_p4 = 32'd0;
    end else begin
        ap_phi_mux_sum_V_new_0_phi_fu_335_p4 = sum_V_new_0_reg_332;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1065_fu_1510_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln1065_reg_1949 == 1'd1)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state9_io) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1))) & (icmp_ln1065_fu_1510_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if ((~((1'b1 == ap_block_state9_io) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1))) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((1'b1 == ap_block_state10_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1))) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln886_fu_1515_p2 = (count_V + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1)));
end

always @ (*) begin
    ap_block_state10_io = ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_1949 == 1'd1));
end

always @ (*) begin
    ap_block_state9 = ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state9_io = ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_fu_1510_p2 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_8_fu_362_p2 = (count_V ^ 2'd3);

assign icmp_ln1065_fu_1510_p2 = ((count_V == 2'd3) ? 1'b1 : 1'b0);

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign lhs_V_1_fu_1144_p3 = {{tmp_5_fu_1134_p4}, {15'd0}};

assign lhs_V_2_fu_1217_p3 = {{tmp_7_reg_1798}, {15'd0}};

assign lhs_V_3_fu_1239_p3 = {{tmp_10_fu_1229_p4}, {15'd0}};

assign lhs_V_4_fu_1341_p3 = {{tmp_12_reg_1843}, {15'd0}};

assign lhs_V_5_fu_1363_p3 = {{tmp_14_fu_1353_p4}, {15'd0}};

assign lhs_V_6_fu_1410_p3 = {{tmp_16_reg_1893}, {15'd0}};

assign lhs_V_7_fu_1432_p3 = {{tmp_18_fu_1422_p4}, {15'd0}};

assign lhs_V_8_fu_1455_p3 = {{tmp_20_reg_1928}, {15'd0}};

assign lhs_V_9_fu_1477_p3 = {{tmp_22_fu_1467_p4}, {15'd0}};

assign lhs_V_fu_1122_p3 = {{tmp_3_reg_1753}, {15'd0}};

assign output_r_TDATA_int_regslice = (sum_V + sum_each_V_reg_1938);

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign ret_V_1_fu_1152_p2 = (lhs_V_1_fu_1144_p3 + mul_ln1393_1_reg_1758);

assign ret_V_2_fu_1224_p2 = (lhs_V_2_fu_1217_p3 + mul_ln1393_2_reg_1793);

assign ret_V_3_fu_1247_p2 = (lhs_V_3_fu_1239_p3 + mul_ln1393_3_reg_1803);

assign ret_V_4_fu_1348_p2 = (lhs_V_4_fu_1341_p3 + mul_ln1393_4_reg_1838);

assign ret_V_5_fu_1371_p2 = (lhs_V_5_fu_1363_p3 + mul_ln1393_5_reg_1848);

assign ret_V_6_fu_1417_p2 = (lhs_V_6_fu_1410_p3 + mul_ln1393_6_reg_1888);

assign ret_V_7_fu_1440_p2 = (lhs_V_7_fu_1432_p3 + mul_ln1393_7_reg_1898);

assign ret_V_8_fu_1462_p2 = (lhs_V_8_fu_1455_p3 + mul_ln1393_8_reg_1923);

assign ret_V_9_fu_1485_p2 = (lhs_V_9_fu_1477_p3 + mul_ln1393_9_reg_1933);

assign ret_V_fu_1129_p2 = (lhs_V_fu_1122_p3 + mul_ln1393_reg_1748);

assign temp_data_V_fu_1504_p2 = (sum_V + sum_each_V_reg_1938);

assign tmp_10_fu_1229_p4 = {{ret_V_2_fu_1224_p2[46:15]}};

assign tmp_14_fu_1353_p4 = {{ret_V_4_fu_1348_p2[46:15]}};

assign tmp_18_fu_1422_p4 = {{ret_V_6_fu_1417_p2[46:15]}};

assign tmp_22_fu_1467_p4 = {{ret_V_8_fu_1462_p2[46:15]}};

assign tmp_5_fu_1134_p4 = {{ret_V_fu_1129_p2[46:15]}};


reg find_kernel_block = 0;
// synthesis translate_off
`include "low_pass_filter_first_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //low_pass_filter_first

