-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_decimation_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fir_decimation_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_decimation_filter_fir_decimation_filter,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.471000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=334,HLS_SYN_LUT=411,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv16_FFB7 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110110111";
    constant ap_const_lv16_FF1D : STD_LOGIC_VECTOR (15 downto 0) := "1111111100011101";
    constant ap_const_lv16_FF9E : STD_LOGIC_VECTOR (15 downto 0) := "1111111110011110";
    constant ap_const_lv16_F9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011111001";
    constant ap_const_lv16_271 : STD_LOGIC_VECTOR (15 downto 0) := "0000001001110001";
    constant ap_const_lv16_276 : STD_LOGIC_VECTOR (15 downto 0) := "0000001001110110";
    constant ap_const_lv16_F9FA : STD_LOGIC_VECTOR (15 downto 0) := "1111100111111010";
    constant ap_const_lv16_F9E6 : STD_LOGIC_VECTOR (15 downto 0) := "1111100111100110";
    constant ap_const_lv16_FE36 : STD_LOGIC_VECTOR (15 downto 0) := "1111111000110110";
    constant ap_const_lv16_1D1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111010001";
    constant ap_const_lv16_120F : STD_LOGIC_VECTOR (15 downto 0) := "0001001000001111";
    constant ap_const_lv16_217C : STD_LOGIC_VECTOR (15 downto 0) := "0010000101111100";
    constant ap_const_lv16_27EE : STD_LOGIC_VECTOR (15 downto 0) := "0010011111101110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal count_V : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal sum_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln1065_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln1065_reg_787 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_673 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln42_fu_192_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln42_reg_681 : STD_LOGIC_VECTOR (32 downto 0);
    signal r_V_7_fu_216_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_7_reg_688 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_3_fu_322_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_3_reg_696 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_fu_388_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_reg_701 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_6_fu_534_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_736 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_656_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln859_reg_771 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_648_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal output_temp_data_V_fu_599_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_temp_data_V_reg_781 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_sum_V_new_0_phi_fu_163_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal regslice_both_output_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state7 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal add_ln886_fu_611_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal r_V_5_fu_256_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln42_fu_232_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal count_V_load_cast_fu_182_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_i_i220_fu_186_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_468_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_492_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_515_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_552_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_634_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_641_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln859_1_fu_587_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_664_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln859_2_fu_596_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln859_1_fu_590_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_634_ce : STD_LOGIC;
    signal grp_fu_641_ce : STD_LOGIC;
    signal grp_fu_664_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_decimation_filter_mux_533_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (32 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component fir_decimation_filter_mux_533_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (32 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_decimation_filter_mul_mul_16s_8s_24_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fir_decimation_filter_mac_muladd_16s_8s_24s_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component fir_decimation_filter_mac_muladd_16s_8s_25s_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (24 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component fir_decimation_filter_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mux_533_8_1_1_U1 : component fir_decimation_filter_mux_533_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 33,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16,
        din1 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12,
        din2 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8,
        din3 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4,
        din4 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E,
        din5 => sext_ln42_fu_192_p1,
        dout => r_V_7_fu_216_p7);

    mux_533_8_1_1_U2 : component fir_decimation_filter_mux_533_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 33,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17,
        din1 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13,
        din2 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9,
        din3 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5,
        din4 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1,
        din5 => sext_ln42_fu_192_p1,
        dout => r_V_5_fu_256_p7);

    mux_533_8_1_1_U3 : component fir_decimation_filter_mux_533_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 33,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18,
        din1 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14,
        din2 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10,
        din3 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6,
        din4 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2,
        din5 => sext_ln42_fu_192_p1,
        dout => r_V_3_fu_322_p7);

    mux_533_8_1_1_U4 : component fir_decimation_filter_mux_533_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 33,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19,
        din1 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15,
        din2 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11,
        din3 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7,
        din4 => p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3,
        din5 => sext_ln42_fu_192_p1,
        dout => r_V_fu_388_p7);

    mux_533_16_1_1_U5 : component fir_decimation_filter_mux_533_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 33,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_FFB7,
        din1 => ap_const_lv16_FF1D,
        din2 => ap_const_lv16_FF9E,
        din3 => ap_const_lv16_F9,
        din4 => ap_const_lv16_271,
        din5 => sext_ln42_fu_192_p1,
        dout => tmp_4_fu_468_p7);

    mux_533_16_1_1_U6 : component fir_decimation_filter_mux_533_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 33,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_276,
        din1 => ap_const_lv16_F9FA,
        din2 => ap_const_lv16_F9E6,
        din3 => ap_const_lv16_FE36,
        din4 => ap_const_lv16_1D1,
        din5 => sext_ln42_fu_192_p1,
        dout => tmp_7_fu_492_p7);

    mux_533_16_1_1_U7 : component fir_decimation_filter_mux_533_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 33,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_1D1,
        din1 => ap_const_lv16_FE36,
        din2 => ap_const_lv16_F9E6,
        din3 => ap_const_lv16_F9FA,
        din4 => ap_const_lv16_276,
        din5 => sext_ln42_reg_681,
        dout => tmp_5_fu_515_p7);

    mux_533_16_1_1_U8 : component fir_decimation_filter_mux_533_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 33,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_120F,
        din1 => ap_const_lv16_217C,
        din2 => ap_const_lv16_27EE,
        din3 => ap_const_lv16_217C,
        din4 => ap_const_lv16_120F,
        din5 => sext_ln42_reg_681,
        dout => tmp_6_fu_534_p7);

    mux_533_16_1_1_U9 : component fir_decimation_filter_mux_533_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 33,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_271,
        din1 => ap_const_lv16_F9,
        din2 => ap_const_lv16_FF9E,
        din3 => ap_const_lv16_FF1D,
        din4 => ap_const_lv16_FFB7,
        din5 => sext_ln42_reg_681,
        dout => tmp_8_fu_552_p7);

    mul_mul_16s_8s_24_4_1_U10 : component fir_decimation_filter_mul_mul_16s_8s_24_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_4_fu_468_p7,
        din1 => input_r_TDATA_int_regslice,
        ce => grp_fu_634_ce,
        dout => grp_fu_634_p2);

    mul_mul_16s_8s_24_4_1_U11 : component fir_decimation_filter_mul_mul_16s_8s_24_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_7_fu_492_p7,
        din1 => r_V_5_fu_256_p7,
        ce => grp_fu_641_ce,
        dout => grp_fu_641_p2);

    mac_muladd_16s_8s_24s_25_4_1_U12 : component fir_decimation_filter_mac_muladd_16s_8s_24s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        din2_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_5_fu_515_p7,
        din1 => r_V_reg_701,
        din2 => grp_fu_634_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_648_p3);

    mac_muladd_16s_8s_24s_25_4_1_U13 : component fir_decimation_filter_mac_muladd_16s_8s_24s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        din2_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_8_fu_552_p7,
        din1 => r_V_7_reg_688,
        din2 => grp_fu_641_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_656_p3);

    mac_muladd_16s_8s_25s_25_4_1_U14 : component fir_decimation_filter_mac_muladd_16s_8s_25s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        din2_WIDTH => 25,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_6_reg_736,
        din1 => r_V_3_reg_696,
        din2 => grp_fu_648_p3,
        ce => grp_fu_664_ce,
        dout => grp_fu_664_p3);

    regslice_both_input_r_V_data_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_data_V_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_data_V_U_apdone_blk);

    regslice_both_input_r_V_keep_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TKEEP,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_keep_V_U_ack_in,
        data_out => input_r_TKEEP_int_regslice,
        vld_out => regslice_both_input_r_V_keep_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_keep_V_U_apdone_blk);

    regslice_both_input_r_V_strb_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TSTRB,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_strb_V_U_ack_in,
        data_out => input_r_TSTRB_int_regslice,
        vld_out => regslice_both_input_r_V_strb_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_strb_V_U_apdone_blk);

    regslice_both_input_r_V_last_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TLAST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_last_V_U_ack_in,
        data_out => input_r_TLAST_int_regslice,
        vld_out => regslice_both_input_r_V_last_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_last_V_U_apdone_blk);

    regslice_both_output_r_V_data_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_V_data_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_data_V_U_apdone_blk);

    regslice_both_output_r_V_keep_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_keep_V_U_ack_in_dummy,
        data_out => output_r_TKEEP,
        vld_out => regslice_both_output_r_V_keep_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_keep_V_U_apdone_blk);

    regslice_both_output_r_V_strb_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_strb_V_U_ack_in_dummy,
        data_out => output_r_TSTRB,
        vld_out => regslice_both_output_r_V_strb_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_strb_V_U_apdone_blk);

    regslice_both_output_r_V_last_V_U : component fir_decimation_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_673,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_last_V_U_ack_in_dummy,
        data_out => output_r_TLAST,
        vld_out => regslice_both_output_r_V_last_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    count_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln1065_fu_606_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                count_V <= add_ln886_fu_611_p2;
            elsif ((not(((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln1065_reg_787 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                count_V <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln859_reg_771 <= grp_fu_656_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln1065_reg_787 <= icmp_ln1065_fu_606_p2;
                output_temp_data_V_reg_781 <= output_temp_data_V_fu_599_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((trunc_ln42_fu_232_p1 = ap_const_lv3_3)) and not((trunc_ln42_fu_232_p1 = ap_const_lv3_2)) and not((trunc_ln42_fu_232_p1 = ap_const_lv3_1)) and not((trunc_ln42_fu_232_p1 = ap_const_lv3_0)) and (input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E <= r_V_5_fu_256_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_1 <= r_V_3_fu_322_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_2 <= r_V_fu_388_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_3 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln42_fu_232_p1 = ap_const_lv3_2))) then
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_10 <= r_V_fu_388_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_11 <= input_r_TDATA_int_regslice;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_8 <= r_V_5_fu_256_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_9 <= r_V_3_fu_322_p7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln42_fu_232_p1 = ap_const_lv3_1))) then
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_12 <= r_V_5_fu_256_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_13 <= r_V_3_fu_322_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_14 <= r_V_fu_388_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_15 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln42_fu_232_p1 = ap_const_lv3_0))) then
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_16 <= r_V_5_fu_256_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_17 <= r_V_3_fu_322_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_18 <= r_V_fu_388_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_19 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln42_fu_232_p1 = ap_const_lv3_3))) then
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_4 <= r_V_5_fu_256_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_5 <= r_V_3_fu_322_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_6 <= r_V_fu_388_p7;
                p_ZZ21fir_decimation_filterRN3hls6streamINS_4axisI8ap_fixedILi8ELi1EL9ap_q_mode5E_7 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                r_V_3_reg_696 <= r_V_3_fu_322_p7;
                r_V_7_reg_688 <= r_V_7_fu_216_p7;
                r_V_reg_701 <= r_V_fu_388_p7;
                sext_ln42_reg_681 <= sext_ln42_fu_192_p1;
                tmp_last_V_reg_673 <= input_r_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                sum_V <= ap_phi_mux_sum_V_new_0_phi_fu_163_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_6_reg_736 <= tmp_6_fu_534_p7;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, icmp_ln1065_fu_606_p2, ap_CS_fsm_state7, icmp_ln1065_reg_787, regslice_both_output_r_V_data_V_U_apdone_blk, ap_block_state7_io, ap_block_state6_io, input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln859_1_fu_590_p2 <= std_logic_vector(signed(sext_ln859_1_fu_587_p1) + signed(sum_V));
    add_ln886_fu_611_p2 <= std_logic_vector(unsigned(count_V) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(input_r_TVALID_int_regslice)
    begin
        if ((input_r_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(icmp_ln1065_fu_606_p2, ap_block_state6_io, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(icmp_ln1065_reg_787, regslice_both_output_r_V_data_V_U_apdone_blk, ap_block_state7_io, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state6_assign_proc : process(icmp_ln1065_fu_606_p2, output_r_TREADY_int_regslice)
    begin
                ap_block_state6 <= ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state6_io_assign_proc : process(icmp_ln1065_fu_606_p2, output_r_TREADY_int_regslice)
    begin
                ap_block_state6_io <= ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(icmp_ln1065_reg_787, regslice_both_output_r_V_data_V_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state7 <= ((regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state7_io_assign_proc : process(icmp_ln1065_reg_787, output_r_TREADY_int_regslice)
    begin
                ap_block_state7_io <= ((icmp_ln1065_reg_787 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_phi_mux_sum_V_new_0_phi_fu_163_p4_assign_proc : process(ap_CS_fsm_state7, icmp_ln1065_reg_787, output_temp_data_V_reg_781)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((icmp_ln1065_reg_787 = ap_const_lv1_0)) then 
                ap_phi_mux_sum_V_new_0_phi_fu_163_p4 <= output_temp_data_V_reg_781;
            elsif ((icmp_ln1065_reg_787 = ap_const_lv1_1)) then 
                ap_phi_mux_sum_V_new_0_phi_fu_163_p4 <= ap_const_lv32_0;
            else 
                ap_phi_mux_sum_V_new_0_phi_fu_163_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_sum_V_new_0_phi_fu_163_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    count_V_load_cast_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(count_V),4));

    grp_fu_634_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_634_ce <= ap_const_logic_1;
        else 
            grp_fu_634_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_641_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_641_ce <= ap_const_logic_1;
        else 
            grp_fu_641_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_664_ce_assign_proc : process(ap_CS_fsm_state6, icmp_ln1065_fu_606_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_block_state6_io, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            grp_fu_664_ce <= ap_const_logic_1;
        else 
            grp_fu_664_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1065_fu_606_p2 <= "1" when (count_V = ap_const_lv3_4) else "0";

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_V_data_V_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state6, icmp_ln1065_fu_606_p2, ap_CS_fsm_state7, icmp_ln1065_reg_787, output_r_TREADY_int_regslice)
    begin
        if ((((icmp_ln1065_reg_787 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_r_TDATA_int_regslice <= std_logic_vector(signed(sext_ln859_2_fu_596_p1) + signed(add_ln859_1_fu_590_p2));
    output_r_TVALID <= regslice_both_output_r_V_data_V_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state6, icmp_ln1065_fu_606_p2, ap_block_state6_io, output_r_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (output_r_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln1065_fu_606_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    output_temp_data_V_fu_599_p2 <= std_logic_vector(signed(sext_ln859_2_fu_596_p1) + signed(add_ln859_1_fu_590_p2));
        sext_ln42_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_i_i220_fu_186_p2),33));

        sext_ln859_1_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln859_reg_771),32));

        sext_ln859_2_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_664_p3),32));

    sub_i_i220_fu_186_p2 <= std_logic_vector(unsigned(ap_const_lv4_4) - unsigned(count_V_load_cast_fu_182_p1));
    trunc_ln42_fu_232_p1 <= sub_i_i220_fu_186_p2(3 - 1 downto 0);
end behav;
