// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="quadrature_demodulator_quadrature_demodulator,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=700,HLS_SYN_LUT=301,HLS_VERSION=2022_1}" *)

module quadrature_demodulator (
        ap_clk,
        ap_rst_n,
        real_r_TDATA,
        real_r_TVALID,
        real_r_TREADY,
        real_r_TKEEP,
        real_r_TSTRB,
        real_r_TLAST,
        imag_TDATA,
        imag_TVALID,
        imag_TREADY,
        imag_TKEEP,
        imag_TSTRB,
        imag_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [31:0] real_r_TDATA;
input   real_r_TVALID;
output   real_r_TREADY;
input  [3:0] real_r_TKEEP;
input  [3:0] real_r_TSTRB;
input  [0:0] real_r_TLAST;
input  [31:0] imag_TDATA;
input   imag_TVALID;
output   imag_TREADY;
input  [3:0] imag_TKEEP;
input  [3:0] imag_TSTRB;
input  [0:0] imag_TLAST;
output  [31:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [3:0] output_r_TKEEP;
output  [3:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [31:0] quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real;
reg   [31:0] quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1;
reg   [31:0] quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag;
reg   [31:0] quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1;
reg    real_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    imag_TDATA_blk_n;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg  signed [31:0] tmp_data_V_1_reg_211;
reg   [0:0] tmp_last_V_reg_216;
reg  signed [31:0] tmp_data_V_2_reg_221;
wire   [31:0] diff_real_V_fu_160_p2;
reg  signed [31:0] diff_real_V_reg_226;
wire   [31:0] diff_imag_V_fu_166_p2;
reg  signed [31:0] diff_imag_V_reg_231;
wire    ap_CS_fsm_state2;
wire   [53:0] grp_fu_178_p2;
reg   [53:0] r_V_1_reg_256;
wire    ap_CS_fsm_state3;
wire   [53:0] grp_fu_190_p2;
reg   [53:0] r_V_3_reg_261;
reg    ap_block_state1;
wire  signed [31:0] diff_real_V_fu_160_p0;
wire  signed [31:0] diff_imag_V_fu_166_p0;
wire   [53:0] ret_V_fu_196_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
reg    ap_block_state5;
wire    regslice_both_real_r_V_data_V_U_apdone_blk;
wire   [31:0] real_r_TDATA_int_regslice;
wire    real_r_TVALID_int_regslice;
reg    real_r_TREADY_int_regslice;
wire    regslice_both_real_r_V_data_V_U_ack_in;
wire    regslice_both_real_r_V_keep_V_U_apdone_blk;
wire   [3:0] real_r_TKEEP_int_regslice;
wire    regslice_both_real_r_V_keep_V_U_vld_out;
wire    regslice_both_real_r_V_keep_V_U_ack_in;
wire    regslice_both_real_r_V_strb_V_U_apdone_blk;
wire   [3:0] real_r_TSTRB_int_regslice;
wire    regslice_both_real_r_V_strb_V_U_vld_out;
wire    regslice_both_real_r_V_strb_V_U_ack_in;
wire    regslice_both_real_r_V_last_V_U_apdone_blk;
wire   [0:0] real_r_TLAST_int_regslice;
wire    regslice_both_real_r_V_last_V_U_vld_out;
wire    regslice_both_real_r_V_last_V_U_ack_in;
wire    regslice_both_imag_V_data_V_U_apdone_blk;
wire   [31:0] imag_TDATA_int_regslice;
wire    imag_TVALID_int_regslice;
reg    imag_TREADY_int_regslice;
wire    regslice_both_imag_V_data_V_U_ack_in;
wire    regslice_both_imag_V_keep_V_U_apdone_blk;
wire   [3:0] imag_TKEEP_int_regslice;
wire    regslice_both_imag_V_keep_V_U_vld_out;
wire    regslice_both_imag_V_keep_V_U_ack_in;
wire    regslice_both_imag_V_strb_V_U_apdone_blk;
wire   [3:0] imag_TSTRB_int_regslice;
wire    regslice_both_imag_V_strb_V_U_vld_out;
wire    regslice_both_imag_V_strb_V_U_ack_in;
wire    regslice_both_imag_V_last_V_U_apdone_blk;
wire   [0:0] imag_TLAST_int_regslice;
wire    regslice_both_imag_V_last_V_U_vld_out;
wire    regslice_both_imag_V_last_V_U_ack_in;
wire   [31:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real = 32'd0;
#0 quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1 = 32'd0;
#0 quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag = 32'd0;
#0 quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1 = 32'd0;
#0 ap_CS_fsm = 5'd1;
end

quadrature_demodulator_mul_32s_32s_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_32s_32s_54_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(diff_imag_V_reg_231),
    .din1(tmp_data_V_1_reg_211),
    .ce(1'b1),
    .dout(grp_fu_178_p2)
);

quadrature_demodulator_mul_32s_32s_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_32s_32s_54_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(diff_real_V_reg_226),
    .din1(tmp_data_V_2_reg_221),
    .ce(1'b1),
    .dout(grp_fu_190_p2)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_real_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_r_TDATA),
    .vld_in(real_r_TVALID),
    .ack_in(regslice_both_real_r_V_data_V_U_ack_in),
    .data_out(real_r_TDATA_int_regslice),
    .vld_out(real_r_TVALID_int_regslice),
    .ack_out(real_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_r_V_data_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_r_TKEEP),
    .vld_in(real_r_TVALID),
    .ack_in(regslice_both_real_r_V_keep_V_U_ack_in),
    .data_out(real_r_TKEEP_int_regslice),
    .vld_out(regslice_both_real_r_V_keep_V_U_vld_out),
    .ack_out(real_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_r_V_keep_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_r_TSTRB),
    .vld_in(real_r_TVALID),
    .ack_in(regslice_both_real_r_V_strb_V_U_ack_in),
    .data_out(real_r_TSTRB_int_regslice),
    .vld_out(regslice_both_real_r_V_strb_V_U_vld_out),
    .ack_out(real_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_r_V_strb_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_real_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_r_TLAST),
    .vld_in(real_r_TVALID),
    .ack_in(regslice_both_real_r_V_last_V_U_ack_in),
    .data_out(real_r_TLAST_int_regslice),
    .vld_out(regslice_both_real_r_V_last_V_U_vld_out),
    .ack_out(real_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_r_V_last_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_imag_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_TDATA),
    .vld_in(imag_TVALID),
    .ack_in(regslice_both_imag_V_data_V_U_ack_in),
    .data_out(imag_TDATA_int_regslice),
    .vld_out(imag_TVALID_int_regslice),
    .ack_out(imag_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_V_data_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_TKEEP),
    .vld_in(imag_TVALID),
    .ack_in(regslice_both_imag_V_keep_V_U_ack_in),
    .data_out(imag_TKEEP_int_regslice),
    .vld_out(regslice_both_imag_V_keep_V_U_vld_out),
    .ack_out(imag_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_V_keep_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_TSTRB),
    .vld_in(imag_TVALID),
    .ack_in(regslice_both_imag_V_strb_V_U_ack_in),
    .data_out(imag_TSTRB_int_regslice),
    .vld_out(regslice_both_imag_V_strb_V_U_vld_out),
    .ack_out(imag_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_V_strb_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imag_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_TLAST),
    .vld_in(imag_TVALID),
    .ack_in(regslice_both_imag_V_last_V_U_ack_in),
    .data_out(imag_TLAST_int_regslice),
    .vld_out(regslice_both_imag_V_last_V_U_vld_out),
    .ack_out(imag_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_V_last_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

quadrature_demodulator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_216),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        diff_imag_V_reg_231 <= diff_imag_V_fu_166_p2;
        diff_real_V_reg_226 <= diff_real_V_fu_160_p2;
        tmp_data_V_1_reg_211 <= real_r_TDATA_int_regslice;
        tmp_data_V_2_reg_221 <= imag_TDATA_int_regslice;
        tmp_last_V_reg_216 <= real_r_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag <= quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1;
        quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag_1 <= imag_TDATA_int_regslice;
        quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real <= quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1;
        quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real_1 <= real_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_V_1_reg_256 <= grp_fu_178_p2;
        r_V_3_reg_261 <= grp_fu_190_p2;
    end
end

always @ (*) begin
    if (((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((output_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output_r_TREADY_int_regslice == 1'b0) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        imag_TDATA_blk_n = imag_TVALID_int_regslice;
    end else begin
        imag_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        imag_TREADY_int_regslice = 1'b1;
    end else begin
        imag_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((output_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        real_r_TDATA_blk_n = real_r_TVALID_int_regslice;
    end else begin
        real_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        real_r_TREADY_int_regslice = 1'b1;
    end else begin
        real_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((output_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((output_r_TREADY_int_regslice == 1'b0) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((imag_TVALID_int_regslice == 1'b0) | (real_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((output_r_TREADY_int_regslice == 1'b0) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign diff_imag_V_fu_166_p0 = imag_TDATA_int_regslice;

assign diff_imag_V_fu_166_p2 = ($signed(diff_imag_V_fu_166_p0) - $signed(quadrature_demodulator_stream_stream_stream_axis_0_shift_register_imag));

assign diff_real_V_fu_160_p0 = real_r_TDATA_int_regslice;

assign diff_real_V_fu_160_p2 = ($signed(diff_real_V_fu_160_p0) - $signed(quadrature_demodulator_stream_stream_stream_axis_0_shift_register_real));

assign imag_TREADY = regslice_both_imag_V_data_V_U_ack_in;

assign output_r_TDATA_int_regslice = {{ret_V_fu_196_p2[53:22]}};

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign real_r_TREADY = regslice_both_real_r_V_data_V_U_ack_in;

assign ret_V_fu_196_p2 = (r_V_1_reg_256 - r_V_3_reg_261);


reg find_kernel_block = 0;
// synthesis translate_off
`include "quadrature_demodulator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //quadrature_demodulator

