// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="low_pass_filter_second_low_pass_filter_second,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8381,HLS_SYN_LUT=3194,HLS_VERSION=2022_1}" *)

module low_pass_filter_second (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [3:0] input_r_TKEEP;
input  [3:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [1:0] output_r_TKEEP;
output  [1:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;

 reg    ap_rst_n_inv;
reg   [1:0] count_V;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_30;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_8;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_32;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_10;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_33;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_11;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_34;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_12;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_35;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_13;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_36;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_14;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_37;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_15;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_38;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_16;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_39;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_17;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_40;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_18;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_41;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_19;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_22;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_23;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_1;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_24;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_2;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_25;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_3;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_26;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_4;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_27;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_5;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_28;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_6;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_31;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_9;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_42;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_20;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_43;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_21;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_29;
reg   [31:0] p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_7;
reg   [31:0] sum_V;
reg    input_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln1065_fu_2261_p2;
wire    ap_CS_fsm_state15;
reg   [0:0] icmp_ln1065_reg_3161;
reg  signed [31:0] tmp_data_V_1_reg_2300;
reg   [0:0] tmp_last_V_reg_2305;
wire  signed [32:0] sext_ln39_fu_500_p1;
reg  signed [32:0] sext_ln39_reg_2313;
wire   [31:0] tmp_1_fu_686_p4;
wire   [31:0] tmp_2_fu_696_p4;
wire   [31:0] tmp_3_fu_706_p4;
wire   [31:0] tmp_4_fu_716_p4;
wire   [31:0] tmp_5_fu_726_p4;
wire   [31:0] tmp_6_fu_736_p4;
wire   [31:0] tmp_7_fu_746_p4;
wire   [31:0] tmp_8_fu_756_p4;
wire   [31:0] tmp_9_fu_766_p4;
wire   [31:0] tmp_s_fu_776_p4;
wire   [31:0] tmp_10_fu_786_p4;
wire   [31:0] tmp_11_fu_796_p4;
wire   [31:0] tmp_12_fu_806_p4;
wire  signed [31:0] r_V_7_fu_816_p4;
reg  signed [31:0] r_V_7_reg_2561;
wire  signed [31:0] r_V_6_fu_826_p4;
reg  signed [31:0] r_V_6_reg_2566;
wire  signed [31:0] r_V_5_fu_836_p4;
reg  signed [31:0] r_V_5_reg_2571;
wire  signed [31:0] r_V_4_fu_846_p4;
reg  signed [31:0] r_V_4_reg_2576;
wire  signed [31:0] r_V_3_fu_856_p4;
reg  signed [31:0] r_V_3_reg_2581;
wire  signed [31:0] r_V_2_fu_866_p4;
reg  signed [31:0] r_V_2_reg_2586;
wire  signed [31:0] r_V_1_fu_876_p4;
reg  signed [31:0] r_V_1_reg_2591;
wire   [15:0] tmp_13_fu_1150_p4;
reg  signed [15:0] tmp_13_reg_2596;
wire   [15:0] tmp_14_fu_1160_p4;
reg  signed [15:0] tmp_14_reg_2601;
wire   [15:0] tmp_16_fu_1170_p4;
reg  signed [15:0] tmp_16_reg_2606;
wire    ap_CS_fsm_state2;
wire   [15:0] tmp_18_fu_1216_p4;
reg  signed [15:0] tmp_18_reg_2641;
wire   [15:0] tmp_20_fu_1225_p4;
reg  signed [15:0] tmp_20_reg_2646;
wire   [31:0] r_V_8_fu_1234_p4;
reg  signed [31:0] r_V_8_reg_2651;
wire   [31:0] r_V_9_fu_1243_p4;
reg  signed [31:0] r_V_9_reg_2656;
wire   [31:0] r_V_10_fu_1252_p4;
reg  signed [31:0] r_V_10_reg_2661;
wire   [31:0] r_V_11_fu_1261_p4;
reg  signed [31:0] r_V_11_reg_2666;
wire   [31:0] r_V_12_fu_1270_p4;
reg  signed [31:0] r_V_12_reg_2671;
wire   [31:0] r_V_13_fu_1279_p4;
reg  signed [31:0] r_V_13_reg_2676;
wire   [31:0] r_V_14_fu_1288_p4;
reg  signed [31:0] r_V_14_reg_2681;
wire   [31:0] r_V_15_fu_1297_p4;
reg  signed [31:0] r_V_15_reg_2686;
wire   [31:0] r_V_16_fu_1306_p4;
reg  signed [31:0] r_V_16_reg_2691;
wire   [31:0] r_V_17_fu_1315_p4;
reg  signed [31:0] r_V_17_reg_2696;
wire   [31:0] r_V_18_fu_1324_p4;
reg  signed [31:0] r_V_18_reg_2701;
wire   [31:0] r_V_19_fu_1333_p4;
reg  signed [31:0] r_V_19_reg_2706;
wire   [31:0] r_V_20_fu_1342_p4;
reg  signed [31:0] r_V_20_reg_2711;
wire   [46:0] grp_fu_1198_p2;
reg   [46:0] mul_ln1393_reg_2716;
wire    ap_CS_fsm_state3;
reg   [31:0] tmp_15_reg_2721;
wire   [46:0] grp_fu_1210_p2;
reg   [46:0] mul_ln1393_1_reg_2726;
wire   [15:0] tmp_22_fu_1385_p4;
reg  signed [15:0] tmp_22_reg_2751;
wire   [15:0] tmp_24_fu_1394_p4;
reg  signed [15:0] tmp_24_reg_2756;
wire   [46:0] grp_fu_1367_p2;
reg   [46:0] mul_ln1393_2_reg_2761;
wire    ap_CS_fsm_state4;
reg   [31:0] tmp_19_reg_2766;
wire   [46:0] grp_fu_1379_p2;
reg   [46:0] mul_ln1393_3_reg_2771;
wire   [15:0] tmp_26_fu_1472_p4;
reg  signed [15:0] tmp_26_reg_2796;
wire   [15:0] tmp_28_fu_1481_p4;
reg  signed [15:0] tmp_28_reg_2801;
wire   [46:0] grp_fu_1454_p2;
reg   [46:0] mul_ln1393_4_reg_2806;
wire    ap_CS_fsm_state5;
reg   [31:0] tmp_23_reg_2811;
wire   [46:0] grp_fu_1466_p2;
reg   [46:0] mul_ln1393_5_reg_2816;
wire   [15:0] tmp_30_fu_1559_p4;
reg  signed [15:0] tmp_30_reg_2841;
wire   [15:0] tmp_32_fu_1568_p4;
reg  signed [15:0] tmp_32_reg_2846;
wire   [46:0] grp_fu_1541_p2;
reg   [46:0] mul_ln1393_6_reg_2851;
wire    ap_CS_fsm_state6;
reg   [31:0] tmp_27_reg_2856;
wire   [46:0] grp_fu_1553_p2;
reg   [46:0] mul_ln1393_7_reg_2861;
wire   [15:0] tmp_34_fu_1646_p4;
reg  signed [15:0] tmp_34_reg_2886;
wire   [15:0] tmp_36_fu_1655_p4;
reg  signed [15:0] tmp_36_reg_2891;
wire   [46:0] grp_fu_1628_p2;
reg   [46:0] mul_ln1393_8_reg_2896;
wire    ap_CS_fsm_state7;
reg   [31:0] tmp_31_reg_2901;
wire   [46:0] grp_fu_1640_p2;
reg   [46:0] mul_ln1393_9_reg_2906;
wire   [15:0] tmp_38_fu_1733_p4;
reg  signed [15:0] tmp_38_reg_2931;
wire   [15:0] tmp_40_fu_1742_p4;
reg  signed [15:0] tmp_40_reg_2936;
wire   [46:0] grp_fu_1715_p2;
reg   [46:0] mul_ln1393_10_reg_2941;
wire    ap_CS_fsm_state8;
reg   [31:0] tmp_35_reg_2946;
wire   [46:0] grp_fu_1727_p2;
reg   [46:0] mul_ln1393_11_reg_2951;
wire   [15:0] tmp_42_fu_1820_p4;
reg  signed [15:0] tmp_42_reg_2976;
wire   [15:0] tmp_44_fu_1829_p4;
reg  signed [15:0] tmp_44_reg_2981;
wire   [46:0] grp_fu_1802_p2;
reg   [46:0] mul_ln1393_12_reg_2986;
wire    ap_CS_fsm_state9;
reg   [31:0] tmp_39_reg_2991;
wire   [46:0] grp_fu_1814_p2;
reg   [46:0] mul_ln1393_13_reg_2996;
wire   [15:0] tmp_46_fu_1907_p4;
reg  signed [15:0] tmp_46_reg_3021;
wire   [15:0] tmp_48_fu_1916_p4;
reg  signed [15:0] tmp_48_reg_3026;
wire   [46:0] grp_fu_1889_p2;
reg   [46:0] mul_ln1393_14_reg_3031;
wire    ap_CS_fsm_state10;
reg   [31:0] tmp_43_reg_3036;
wire   [46:0] grp_fu_1901_p2;
reg   [46:0] mul_ln1393_15_reg_3041;
wire   [15:0] tmp_50_fu_1994_p4;
reg  signed [15:0] tmp_50_reg_3066;
wire   [15:0] tmp_52_fu_2003_p4;
reg  signed [15:0] tmp_52_reg_3071;
wire   [46:0] grp_fu_1976_p2;
reg   [46:0] mul_ln1393_16_reg_3076;
wire    ap_CS_fsm_state11;
reg   [31:0] tmp_47_reg_3081;
wire   [46:0] grp_fu_1988_p2;
reg   [46:0] mul_ln1393_17_reg_3086;
wire   [31:0] r_V_21_fu_2089_p4;
reg  signed [31:0] r_V_21_reg_3111;
wire   [15:0] tmp_54_fu_2098_p4;
reg  signed [15:0] tmp_54_reg_3116;
wire   [46:0] grp_fu_2063_p2;
reg   [46:0] mul_ln1393_18_reg_3121;
wire    ap_CS_fsm_state12;
reg   [31:0] tmp_51_reg_3126;
wire   [46:0] grp_fu_2075_p2;
reg   [46:0] mul_ln1393_19_reg_3131;
wire   [46:0] grp_fu_2158_p2;
reg   [46:0] mul_ln1393_20_reg_3146;
wire    ap_CS_fsm_state13;
reg   [31:0] tmp_55_reg_3151;
wire   [31:0] add_ln859_fu_2249_p2;
reg   [31:0] mux_case_1721_reg_238;
wire   [0:0] trunc_ln39_fu_522_p1;
reg   [31:0] mux_case_0720_reg_247;
reg   [31:0] mux_case_1717_reg_256;
reg   [31:0] mux_case_0716_reg_265;
reg   [31:0] mux_case_1713_reg_274;
reg   [31:0] mux_case_0712_reg_283;
reg   [31:0] mux_case_1709_reg_292;
reg   [31:0] mux_case_0708_reg_301;
reg   [31:0] mux_case_1705_reg_310;
reg   [31:0] mux_case_0704_reg_319;
reg   [31:0] mux_case_1701_reg_328;
reg   [31:0] mux_case_0700_reg_337;
reg   [31:0] mux_case_1697_reg_346;
reg   [31:0] mux_case_0696_reg_355;
reg   [31:0] mux_case_1693_reg_364;
reg   [31:0] mux_case_0692_reg_373;
reg   [31:0] mux_case_1689_reg_382;
reg   [31:0] mux_case_0688_reg_391;
reg   [31:0] mux_case_1685_reg_400;
reg   [31:0] mux_case_0684_reg_409;
reg   [31:0] mux_case_06768448518818919259399779951034_reg_418;
reg   [31:0] mux_case_16778428538798939239419759971032_reg_427;
reg   [31:0] mux_case_16818248408558778959219439739991030_reg_436;
reg   [31:0] mux_case_068082683885787589791994597110011028_reg_445;
reg   [31:0] mux_case_167385987389991794796910031026_reg_454;
reg   [31:0] mux_case_067286187190191594996710051024_reg_463;
reg   [31:0] ap_phi_mux_sum_V_new_0_phi_fu_475_p4;
reg   [31:0] sum_V_new_0_reg_472;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
reg    ap_block_state15;
reg    ap_block_state15_io;
reg    ap_block_state14;
reg    ap_block_state14_io;
wire   [1:0] add_ln886_fu_2266_p2;
wire   [31:0] tmp_fu_512_p4;
wire  signed [1:0] sub_i_i226_fu_494_p2;
wire   [46:0] grp_fu_1186_p2;
wire   [46:0] lhs_V_fu_1403_p3;
wire   [46:0] ret_V_fu_1410_p2;
wire   [31:0] tmp_17_fu_1415_p4;
wire   [46:0] lhs_V_1_fu_1425_p3;
wire   [46:0] ret_V_1_fu_1433_p2;
wire   [46:0] lhs_V_2_fu_1490_p3;
wire   [46:0] ret_V_2_fu_1497_p2;
wire   [31:0] tmp_21_fu_1502_p4;
wire   [46:0] lhs_V_3_fu_1512_p3;
wire   [46:0] ret_V_3_fu_1520_p2;
wire   [46:0] lhs_V_4_fu_1577_p3;
wire   [46:0] ret_V_4_fu_1584_p2;
wire   [31:0] tmp_25_fu_1589_p4;
wire   [46:0] lhs_V_5_fu_1599_p3;
wire   [46:0] ret_V_5_fu_1607_p2;
wire   [46:0] lhs_V_6_fu_1664_p3;
wire   [46:0] ret_V_6_fu_1671_p2;
wire   [31:0] tmp_29_fu_1676_p4;
wire   [46:0] lhs_V_7_fu_1686_p3;
wire   [46:0] ret_V_7_fu_1694_p2;
wire   [46:0] lhs_V_8_fu_1751_p3;
wire   [46:0] ret_V_8_fu_1758_p2;
wire   [31:0] tmp_33_fu_1763_p4;
wire   [46:0] lhs_V_9_fu_1773_p3;
wire   [46:0] ret_V_9_fu_1781_p2;
wire   [46:0] lhs_V_10_fu_1838_p3;
wire   [46:0] ret_V_10_fu_1845_p2;
wire   [31:0] tmp_37_fu_1850_p4;
wire   [46:0] lhs_V_11_fu_1860_p3;
wire   [46:0] ret_V_11_fu_1868_p2;
wire   [46:0] lhs_V_12_fu_1925_p3;
wire   [46:0] ret_V_12_fu_1932_p2;
wire   [31:0] tmp_41_fu_1937_p4;
wire   [46:0] lhs_V_13_fu_1947_p3;
wire   [46:0] ret_V_13_fu_1955_p2;
wire   [46:0] lhs_V_14_fu_2012_p3;
wire   [46:0] ret_V_14_fu_2019_p2;
wire   [31:0] tmp_45_fu_2024_p4;
wire   [46:0] lhs_V_15_fu_2034_p3;
wire   [46:0] ret_V_15_fu_2042_p2;
wire   [46:0] lhs_V_16_fu_2107_p3;
wire   [46:0] ret_V_16_fu_2114_p2;
wire   [31:0] tmp_49_fu_2119_p4;
wire   [46:0] lhs_V_17_fu_2129_p3;
wire   [46:0] ret_V_17_fu_2137_p2;
wire   [46:0] lhs_V_18_fu_2164_p3;
wire   [46:0] ret_V_18_fu_2171_p2;
wire   [31:0] tmp_53_fu_2176_p4;
wire   [46:0] lhs_V_19_fu_2186_p3;
wire   [46:0] ret_V_19_fu_2194_p2;
wire   [46:0] lhs_V_20_fu_2209_p3;
wire   [46:0] ret_V_20_fu_2216_p2;
wire   [31:0] sum_each_V_fu_2221_p4;
wire   [22:0] trunc_ln859_fu_2245_p1;
wire   [22:0] trunc_ln1_fu_2235_p4;
wire   [22:0] add_ln1065_fu_2255_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire   [31:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [3:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [3:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire   [15:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 count_V = 2'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_30 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_8 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_32 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_10 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_33 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_11 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_34 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_12 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_35 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_13 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_36 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_14 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_37 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_15 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_38 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_16 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_39 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_17 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_40 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_18 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_41 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_19 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_22 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_23 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_1 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_24 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_2 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_25 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_3 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_26 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_4 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_27 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_5 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_28 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_6 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_31 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_9 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_42 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_20 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_43 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_21 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_29 = 32'd0;
#0 p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_7 = 32'd0;
#0 sum_V = 32'd0;
#0 ap_CS_fsm = 15'd1;
end

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U1(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_30),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_8),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_fu_512_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U2(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_32),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_10),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_1_fu_686_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U3(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_33),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_11),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_2_fu_696_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U4(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_34),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_12),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_3_fu_706_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U5(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_35),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_13),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_4_fu_716_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U6(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_36),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_14),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_5_fu_726_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U7(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_37),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_15),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_6_fu_736_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U8(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_38),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_16),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_7_fu_746_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U9(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_39),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_17),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_8_fu_756_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U10(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_40),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_18),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_9_fu_766_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U11(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_41),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_19),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_s_fu_776_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U12(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_22),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_10_fu_786_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U13(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_23),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_1),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_11_fu_796_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U14(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_24),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_2),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_12_fu_806_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U15(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_25),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_3),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_7_fu_816_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U16(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_26),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_4),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_6_fu_826_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U17(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_27),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_5),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_5_fu_836_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U18(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_28),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_6),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_4_fu_846_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U19(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_31),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_9),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_3_fu_856_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U20(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_42),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_20),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_2_fu_866_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U21(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_43),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_21),
    .din2(sext_ln39_fu_500_p1),
    .dout(r_V_1_fu_876_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U22(
    .din0(16'd1294),
    .din1(16'd151),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_13_fu_1150_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U23(
    .din0(16'd65203),
    .din1(16'd65183),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_14_fu_1160_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U24(
    .din0(16'd88),
    .din1(16'd531),
    .din2(sext_ln39_fu_500_p1),
    .dout(tmp_16_fu_1170_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U25(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_data_V_1_reg_2300),
    .din1(tmp_13_reg_2596),
    .ce(1'b1),
    .dout(grp_fu_1186_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_1_reg_2591),
    .din1(tmp_14_reg_2601),
    .ce(1'b1),
    .dout(grp_fu_1198_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U27(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_2_reg_2586),
    .din1(tmp_16_reg_2606),
    .ce(1'b1),
    .dout(grp_fu_1210_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U28(
    .din0(16'd213),
    .din1(16'd65104),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_18_fu_1216_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U29(
    .din0(16'd64922),
    .din1(16'd135),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_20_fu_1225_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U30(
    .din0(mux_case_067286187190191594996710051024_reg_463),
    .din1(mux_case_167385987389991794796910031026_reg_454),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_8_fu_1234_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U31(
    .din0(mux_case_06768448518818919259399779951034_reg_418),
    .din1(mux_case_16778428538798939239419759971032_reg_427),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_9_fu_1243_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U32(
    .din0(mux_case_068082683885787589791994597110011028_reg_445),
    .din1(mux_case_16818248408558778959219439739991030_reg_436),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_10_fu_1252_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U33(
    .din0(mux_case_0684_reg_409),
    .din1(mux_case_1685_reg_400),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_11_fu_1261_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U34(
    .din0(mux_case_0688_reg_391),
    .din1(mux_case_1689_reg_382),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_12_fu_1270_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U35(
    .din0(mux_case_0692_reg_373),
    .din1(mux_case_1693_reg_364),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_13_fu_1279_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U36(
    .din0(mux_case_0696_reg_355),
    .din1(mux_case_1697_reg_346),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_14_fu_1288_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U37(
    .din0(mux_case_0700_reg_337),
    .din1(mux_case_1701_reg_328),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_15_fu_1297_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U38(
    .din0(mux_case_0704_reg_319),
    .din1(mux_case_1705_reg_310),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_16_fu_1306_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U39(
    .din0(mux_case_0708_reg_301),
    .din1(mux_case_1709_reg_292),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_17_fu_1315_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U40(
    .din0(mux_case_0712_reg_283),
    .din1(mux_case_1713_reg_274),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_18_fu_1324_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U41(
    .din0(mux_case_0716_reg_265),
    .din1(mux_case_1717_reg_256),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_19_fu_1333_p4)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U42(
    .din0(mux_case_0720_reg_247),
    .din1(mux_case_1721_reg_238),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_20_fu_1342_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_3_reg_2581),
    .din1(tmp_18_reg_2641),
    .ce(1'b1),
    .dout(grp_fu_1367_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U44(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_4_reg_2576),
    .din1(tmp_20_reg_2646),
    .ce(1'b1),
    .dout(grp_fu_1379_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U45(
    .din0(16'd797),
    .din1(16'd443),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_22_fu_1385_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U46(
    .din0(16'd64822),
    .din1(16'd64486),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_24_fu_1394_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U47(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_5_reg_2571),
    .din1(tmp_22_reg_2751),
    .ce(1'b1),
    .dout(grp_fu_1454_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U48(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_6_reg_2566),
    .din1(tmp_24_reg_2756),
    .ce(1'b1),
    .dout(grp_fu_1466_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U49(
    .din0(16'd121),
    .din1(16'd1525),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_26_fu_1472_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U50(
    .din0(16'd972),
    .din1(16'd64092),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_28_fu_1481_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U51(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_7_reg_2561),
    .din1(tmp_26_reg_2796),
    .ce(1'b1),
    .dout(grp_fu_1541_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U52(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_8_reg_2651),
    .din1(tmp_28_reg_2801),
    .ce(1'b1),
    .dout(grp_fu_1553_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U53(
    .din0(16'd62766),
    .din1(16'd139),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_30_fu_1559_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U54(
    .din0(16'd6641),
    .din1(16'd12149),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_32_fu_1568_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U55(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_9_reg_2656),
    .din1(tmp_30_reg_2841),
    .ce(1'b1),
    .dout(grp_fu_1628_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U56(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_10_reg_2661),
    .din1(tmp_32_reg_2846),
    .ce(1'b1),
    .dout(grp_fu_1640_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U57(
    .din0(16'd12149),
    .din1(16'd6641),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_34_fu_1646_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U58(
    .din0(16'd139),
    .din1(16'd62766),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_36_fu_1655_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U59(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_11_reg_2666),
    .din1(tmp_34_reg_2886),
    .ce(1'b1),
    .dout(grp_fu_1715_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U60(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_12_reg_2671),
    .din1(tmp_36_reg_2891),
    .ce(1'b1),
    .dout(grp_fu_1727_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U61(
    .din0(16'd64092),
    .din1(16'd972),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_38_fu_1733_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U62(
    .din0(16'd1525),
    .din1(16'd121),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_40_fu_1742_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U63(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_13_reg_2676),
    .din1(tmp_38_reg_2931),
    .ce(1'b1),
    .dout(grp_fu_1802_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U64(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_14_reg_2681),
    .din1(tmp_40_reg_2936),
    .ce(1'b1),
    .dout(grp_fu_1814_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U65(
    .din0(16'd64486),
    .din1(16'd64822),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_42_fu_1820_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U66(
    .din0(16'd443),
    .din1(16'd797),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_44_fu_1829_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U67(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_15_reg_2686),
    .din1(tmp_42_reg_2976),
    .ce(1'b1),
    .dout(grp_fu_1889_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U68(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_16_reg_2691),
    .din1(tmp_44_reg_2981),
    .ce(1'b1),
    .dout(grp_fu_1901_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U69(
    .din0(16'd135),
    .din1(16'd64922),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_46_fu_1907_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U70(
    .din0(16'd65104),
    .din1(16'd213),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_48_fu_1916_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U71(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_17_reg_2696),
    .din1(tmp_46_reg_3021),
    .ce(1'b1),
    .dout(grp_fu_1976_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U72(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_18_reg_2701),
    .din1(tmp_48_reg_3026),
    .ce(1'b1),
    .dout(grp_fu_1988_p2)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U73(
    .din0(16'd531),
    .din1(16'd88),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_50_fu_1994_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U74(
    .din0(16'd65183),
    .din1(16'd65203),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_52_fu_2003_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U75(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_19_reg_2706),
    .din1(tmp_50_reg_3066),
    .ce(1'b1),
    .dout(grp_fu_2063_p2)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U76(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_20_reg_2711),
    .din1(tmp_52_reg_3071),
    .ce(1'b1),
    .dout(grp_fu_2075_p2)
);

low_pass_filter_second_mux_233_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 32 ))
mux_233_32_1_1_U77(
    .din0(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_29),
    .din1(p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_7),
    .din2(sext_ln39_reg_2313),
    .dout(r_V_21_fu_2089_p4)
);

low_pass_filter_second_mux_233_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 16 ))
mux_233_16_1_1_U78(
    .din0(16'd151),
    .din1(16'd1294),
    .din2(sext_ln39_reg_2313),
    .dout(tmp_54_fu_2098_p4)
);

low_pass_filter_second_mul_32s_16s_47_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_32s_16s_47_2_1_U79(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(r_V_21_reg_3111),
    .din1(tmp_54_reg_3116),
    .ce(1'b1),
    .dout(grp_fu_2158_p2)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 2 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 2 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

low_pass_filter_second_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_2305),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state14_io) | ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_fu_2261_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        count_V <= add_ln886_fu_2266_p2;
    end else if ((~((1'b1 == ap_block_state15_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1))) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_reg_3161 == 1'd1))) begin
        count_V <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_067286187190191594996710051024_reg_463 <= tmp_12_fu_806_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_067286187190191594996710051024_reg_463 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_06768448518818919259399779951034_reg_418 <= tmp_11_fu_796_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_06768448518818919259399779951034_reg_418 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_068082683885787589791994597110011028_reg_445 <= tmp_10_fu_786_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_068082683885787589791994597110011028_reg_445 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0684_reg_409 <= tmp_s_fu_776_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0684_reg_409 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0688_reg_391 <= tmp_9_fu_766_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0688_reg_391 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0692_reg_373 <= tmp_8_fu_756_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0692_reg_373 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0696_reg_355 <= tmp_7_fu_746_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0696_reg_355 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0700_reg_337 <= tmp_6_fu_736_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0700_reg_337 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0704_reg_319 <= tmp_5_fu_726_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0704_reg_319 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0708_reg_301 <= tmp_4_fu_716_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0708_reg_301 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0712_reg_283 <= tmp_3_fu_706_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0712_reg_283 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0716_reg_265 <= tmp_2_fu_696_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0716_reg_265 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_0720_reg_247 <= tmp_1_fu_686_p4;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_0720_reg_247 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_167385987389991794796910031026_reg_454 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_1;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_167385987389991794796910031026_reg_454 <= tmp_12_fu_806_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_16778428538798939239419759971032_reg_427 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_16778428538798939239419759971032_reg_427 <= tmp_11_fu_796_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_16818248408558778959219439739991030_reg_436 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_19;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_16818248408558778959219439739991030_reg_436 <= tmp_10_fu_786_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1685_reg_400 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_18;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1685_reg_400 <= tmp_s_fu_776_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1689_reg_382 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_17;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1689_reg_382 <= tmp_9_fu_766_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1693_reg_364 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_16;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1693_reg_364 <= tmp_8_fu_756_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1697_reg_346 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_15;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1697_reg_346 <= tmp_7_fu_746_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1701_reg_328 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_14;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1701_reg_328 <= tmp_6_fu_736_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1705_reg_310 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_13;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1705_reg_310 <= tmp_5_fu_726_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1709_reg_292 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_12;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1709_reg_292 <= tmp_4_fu_716_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1713_reg_274 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_11;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1713_reg_274 <= tmp_3_fu_706_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1717_reg_256 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_10;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1717_reg_256 <= tmp_2_fu_696_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        if ((trunc_ln39_fu_522_p1 == 1'd0)) begin
            mux_case_1721_reg_238 <= p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_8;
        end else if ((trunc_ln39_fu_522_p1 == 1'd1)) begin
            mux_case_1721_reg_238 <= tmp_1_fu_686_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state14_io) | ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_fu_2261_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        sum_V_new_0_reg_472 <= add_ln859_fu_2249_p2;
    end else if ((~((1'b1 == ap_block_state15_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1))) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_reg_3161 == 1'd1))) begin
        sum_V_new_0_reg_472 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        icmp_ln1065_reg_3161 <= icmp_ln1065_fu_2261_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_ln1393_10_reg_2941 <= grp_fu_1715_p2;
        mul_ln1393_11_reg_2951 <= grp_fu_1727_p2;
        tmp_35_reg_2946 <= {{ret_V_9_fu_1781_p2[46:15]}};
        tmp_42_reg_2976 <= tmp_42_fu_1820_p4;
        tmp_44_reg_2981 <= tmp_44_fu_1829_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        mul_ln1393_12_reg_2986 <= grp_fu_1802_p2;
        mul_ln1393_13_reg_2996 <= grp_fu_1814_p2;
        tmp_39_reg_2991 <= {{ret_V_11_fu_1868_p2[46:15]}};
        tmp_46_reg_3021 <= tmp_46_fu_1907_p4;
        tmp_48_reg_3026 <= tmp_48_fu_1916_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        mul_ln1393_14_reg_3031 <= grp_fu_1889_p2;
        mul_ln1393_15_reg_3041 <= grp_fu_1901_p2;
        tmp_43_reg_3036 <= {{ret_V_13_fu_1955_p2[46:15]}};
        tmp_50_reg_3066 <= tmp_50_fu_1994_p4;
        tmp_52_reg_3071 <= tmp_52_fu_2003_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln1393_16_reg_3076 <= grp_fu_1976_p2;
        mul_ln1393_17_reg_3086 <= grp_fu_1988_p2;
        r_V_21_reg_3111 <= r_V_21_fu_2089_p4;
        tmp_47_reg_3081 <= {{ret_V_15_fu_2042_p2[46:15]}};
        tmp_54_reg_3116 <= tmp_54_fu_2098_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        mul_ln1393_18_reg_3121 <= grp_fu_2063_p2;
        mul_ln1393_19_reg_3131 <= grp_fu_2075_p2;
        tmp_51_reg_3126 <= {{ret_V_17_fu_2137_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln1393_1_reg_2726 <= grp_fu_1210_p2;
        mul_ln1393_reg_2716 <= grp_fu_1198_p2;
        tmp_15_reg_2721 <= {{grp_fu_1186_p2[46:15]}};
        tmp_22_reg_2751 <= tmp_22_fu_1385_p4;
        tmp_24_reg_2756 <= tmp_24_fu_1394_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        mul_ln1393_20_reg_3146 <= grp_fu_2158_p2;
        tmp_55_reg_3151 <= {{ret_V_19_fu_2194_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln1393_2_reg_2761 <= grp_fu_1367_p2;
        mul_ln1393_3_reg_2771 <= grp_fu_1379_p2;
        tmp_19_reg_2766 <= {{ret_V_1_fu_1433_p2[46:15]}};
        tmp_26_reg_2796 <= tmp_26_fu_1472_p4;
        tmp_28_reg_2801 <= tmp_28_fu_1481_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln1393_4_reg_2806 <= grp_fu_1454_p2;
        mul_ln1393_5_reg_2816 <= grp_fu_1466_p2;
        tmp_23_reg_2811 <= {{ret_V_3_fu_1520_p2[46:15]}};
        tmp_30_reg_2841 <= tmp_30_fu_1559_p4;
        tmp_32_reg_2846 <= tmp_32_fu_1568_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln1393_6_reg_2851 <= grp_fu_1541_p2;
        mul_ln1393_7_reg_2861 <= grp_fu_1553_p2;
        tmp_27_reg_2856 <= {{ret_V_5_fu_1607_p2[46:15]}};
        tmp_34_reg_2886 <= tmp_34_fu_1646_p4;
        tmp_36_reg_2891 <= tmp_36_fu_1655_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mul_ln1393_8_reg_2896 <= grp_fu_1628_p2;
        mul_ln1393_9_reg_2906 <= grp_fu_1640_p2;
        tmp_31_reg_2901 <= {{ret_V_7_fu_1694_p2[46:15]}};
        tmp_38_reg_2931 <= tmp_38_fu_1733_p4;
        tmp_40_reg_2936 <= tmp_40_fu_1742_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_522_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod <= tmp_11_fu_796_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_1 <= tmp_12_fu_806_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_10 <= tmp_2_fu_696_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_11 <= tmp_3_fu_706_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_12 <= tmp_4_fu_716_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_13 <= tmp_5_fu_726_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_14 <= tmp_6_fu_736_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_15 <= tmp_7_fu_746_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_16 <= tmp_8_fu_756_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_17 <= tmp_9_fu_766_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_18 <= tmp_s_fu_776_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_19 <= tmp_10_fu_786_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_2 <= r_V_7_fu_816_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_20 <= r_V_1_fu_876_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_21 <= input_r_TDATA_int_regslice;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_3 <= r_V_6_fu_826_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_4 <= r_V_5_fu_836_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_5 <= r_V_4_fu_846_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_6 <= r_V_3_fu_856_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_7 <= tmp_fu_512_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_8 <= tmp_1_fu_686_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_9 <= r_V_2_fu_866_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_522_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_22 <= tmp_11_fu_796_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_23 <= tmp_12_fu_806_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_24 <= r_V_7_fu_816_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_25 <= r_V_6_fu_826_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_26 <= r_V_5_fu_836_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_27 <= r_V_4_fu_846_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_28 <= r_V_3_fu_856_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_29 <= tmp_fu_512_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_30 <= tmp_1_fu_686_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_31 <= r_V_2_fu_866_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_32 <= tmp_2_fu_696_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_33 <= tmp_3_fu_706_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_34 <= tmp_4_fu_716_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_35 <= tmp_5_fu_726_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_36 <= tmp_6_fu_736_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_37 <= tmp_7_fu_746_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_38 <= tmp_8_fu_756_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_39 <= tmp_9_fu_766_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_40 <= tmp_s_fu_776_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_41 <= tmp_10_fu_786_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_42 <= r_V_1_fu_876_p4;
        p_ZZ22low_pass_filter_secondRN3hls6streamINS_4axisI8ap_fixedILi32ELi10EL9ap_q_mod_43 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_10_reg_2661 <= r_V_10_fu_1252_p4;
        r_V_11_reg_2666 <= r_V_11_fu_1261_p4;
        r_V_12_reg_2671 <= r_V_12_fu_1270_p4;
        r_V_13_reg_2676 <= r_V_13_fu_1279_p4;
        r_V_14_reg_2681 <= r_V_14_fu_1288_p4;
        r_V_15_reg_2686 <= r_V_15_fu_1297_p4;
        r_V_16_reg_2691 <= r_V_16_fu_1306_p4;
        r_V_17_reg_2696 <= r_V_17_fu_1315_p4;
        r_V_18_reg_2701 <= r_V_18_fu_1324_p4;
        r_V_19_reg_2706 <= r_V_19_fu_1333_p4;
        r_V_20_reg_2711 <= r_V_20_fu_1342_p4;
        r_V_8_reg_2651 <= r_V_8_fu_1234_p4;
        r_V_9_reg_2656 <= r_V_9_fu_1243_p4;
        tmp_18_reg_2641 <= tmp_18_fu_1216_p4;
        tmp_20_reg_2646 <= tmp_20_fu_1225_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        r_V_1_reg_2591 <= r_V_1_fu_876_p4;
        r_V_2_reg_2586 <= r_V_2_fu_866_p4;
        r_V_3_reg_2581 <= r_V_3_fu_856_p4;
        r_V_4_reg_2576 <= r_V_4_fu_846_p4;
        r_V_5_reg_2571 <= r_V_5_fu_836_p4;
        r_V_6_reg_2566 <= r_V_6_fu_826_p4;
        r_V_7_reg_2561 <= r_V_7_fu_816_p4;
        sext_ln39_reg_2313 <= sext_ln39_fu_500_p1;
        tmp_13_reg_2596 <= tmp_13_fu_1150_p4;
        tmp_14_reg_2601 <= tmp_14_fu_1160_p4;
        tmp_16_reg_2606 <= tmp_16_fu_1170_p4;
        tmp_data_V_1_reg_2300 <= input_r_TDATA_int_regslice;
        tmp_last_V_reg_2305 <= input_r_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state15_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1))) & (1'b1 == ap_CS_fsm_state15))) begin
        sum_V <= ap_phi_mux_sum_V_new_0_phi_fu_475_p4;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state14_io) | ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state15_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1)))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_r_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_reg_3161 == 1'd1))) begin
        ap_phi_mux_sum_V_new_0_phi_fu_475_p4 = 32'd0;
    end else begin
        ap_phi_mux_sum_V_new_0_phi_fu_475_p4 = sum_V_new_0_reg_472;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1065_fu_2261_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state15) & (icmp_ln1065_reg_3161 == 1'd1)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state14_io) | ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (icmp_ln1065_fu_2261_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if ((~((1'b1 == ap_block_state14_io) | ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if ((~((1'b1 == ap_block_state15_io) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1))) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1065_fu_2255_p2 = (trunc_ln859_fu_2245_p1 + trunc_ln1_fu_2235_p4);

assign add_ln859_fu_2249_p2 = (sum_V + sum_each_V_fu_2221_p4);

assign add_ln886_fu_2266_p2 = (count_V + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state14 = ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state14_io = ((icmp_ln1065_fu_2261_p2 == 1'd1) & (output_r_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state15 = ((regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1) | ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1)));
end

always @ (*) begin
    ap_block_state15_io = ((output_r_TREADY_int_regslice == 1'b0) & (icmp_ln1065_reg_3161 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln1065_fu_2261_p2 = ((count_V == 2'd1) ? 1'b1 : 1'b0);

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign lhs_V_10_fu_1838_p3 = {{tmp_35_reg_2946}, {15'd0}};

assign lhs_V_11_fu_1860_p3 = {{tmp_37_fu_1850_p4}, {15'd0}};

assign lhs_V_12_fu_1925_p3 = {{tmp_39_reg_2991}, {15'd0}};

assign lhs_V_13_fu_1947_p3 = {{tmp_41_fu_1937_p4}, {15'd0}};

assign lhs_V_14_fu_2012_p3 = {{tmp_43_reg_3036}, {15'd0}};

assign lhs_V_15_fu_2034_p3 = {{tmp_45_fu_2024_p4}, {15'd0}};

assign lhs_V_16_fu_2107_p3 = {{tmp_47_reg_3081}, {15'd0}};

assign lhs_V_17_fu_2129_p3 = {{tmp_49_fu_2119_p4}, {15'd0}};

assign lhs_V_18_fu_2164_p3 = {{tmp_51_reg_3126}, {15'd0}};

assign lhs_V_19_fu_2186_p3 = {{tmp_53_fu_2176_p4}, {15'd0}};

assign lhs_V_1_fu_1425_p3 = {{tmp_17_fu_1415_p4}, {15'd0}};

assign lhs_V_20_fu_2209_p3 = {{tmp_55_reg_3151}, {15'd0}};

assign lhs_V_2_fu_1490_p3 = {{tmp_19_reg_2766}, {15'd0}};

assign lhs_V_3_fu_1512_p3 = {{tmp_21_fu_1502_p4}, {15'd0}};

assign lhs_V_4_fu_1577_p3 = {{tmp_23_reg_2811}, {15'd0}};

assign lhs_V_5_fu_1599_p3 = {{tmp_25_fu_1589_p4}, {15'd0}};

assign lhs_V_6_fu_1664_p3 = {{tmp_27_reg_2856}, {15'd0}};

assign lhs_V_7_fu_1686_p3 = {{tmp_29_fu_1676_p4}, {15'd0}};

assign lhs_V_8_fu_1751_p3 = {{tmp_31_reg_2901}, {15'd0}};

assign lhs_V_9_fu_1773_p3 = {{tmp_33_fu_1763_p4}, {15'd0}};

assign lhs_V_fu_1403_p3 = {{tmp_15_reg_2721}, {15'd0}};

assign output_r_TDATA_int_regslice = {{add_ln1065_fu_2255_p2[22:7]}};

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign ret_V_10_fu_1845_p2 = (lhs_V_10_fu_1838_p3 + mul_ln1393_10_reg_2941);

assign ret_V_11_fu_1868_p2 = (lhs_V_11_fu_1860_p3 + mul_ln1393_11_reg_2951);

assign ret_V_12_fu_1932_p2 = (lhs_V_12_fu_1925_p3 + mul_ln1393_12_reg_2986);

assign ret_V_13_fu_1955_p2 = (lhs_V_13_fu_1947_p3 + mul_ln1393_13_reg_2996);

assign ret_V_14_fu_2019_p2 = (lhs_V_14_fu_2012_p3 + mul_ln1393_14_reg_3031);

assign ret_V_15_fu_2042_p2 = (lhs_V_15_fu_2034_p3 + mul_ln1393_15_reg_3041);

assign ret_V_16_fu_2114_p2 = (lhs_V_16_fu_2107_p3 + mul_ln1393_16_reg_3076);

assign ret_V_17_fu_2137_p2 = (lhs_V_17_fu_2129_p3 + mul_ln1393_17_reg_3086);

assign ret_V_18_fu_2171_p2 = (lhs_V_18_fu_2164_p3 + mul_ln1393_18_reg_3121);

assign ret_V_19_fu_2194_p2 = (lhs_V_19_fu_2186_p3 + mul_ln1393_19_reg_3131);

assign ret_V_1_fu_1433_p2 = (lhs_V_1_fu_1425_p3 + mul_ln1393_1_reg_2726);

assign ret_V_20_fu_2216_p2 = (lhs_V_20_fu_2209_p3 + mul_ln1393_20_reg_3146);

assign ret_V_2_fu_1497_p2 = (lhs_V_2_fu_1490_p3 + mul_ln1393_2_reg_2761);

assign ret_V_3_fu_1520_p2 = (lhs_V_3_fu_1512_p3 + mul_ln1393_3_reg_2771);

assign ret_V_4_fu_1584_p2 = (lhs_V_4_fu_1577_p3 + mul_ln1393_4_reg_2806);

assign ret_V_5_fu_1607_p2 = (lhs_V_5_fu_1599_p3 + mul_ln1393_5_reg_2816);

assign ret_V_6_fu_1671_p2 = (lhs_V_6_fu_1664_p3 + mul_ln1393_6_reg_2851);

assign ret_V_7_fu_1694_p2 = (lhs_V_7_fu_1686_p3 + mul_ln1393_7_reg_2861);

assign ret_V_8_fu_1758_p2 = (lhs_V_8_fu_1751_p3 + mul_ln1393_8_reg_2896);

assign ret_V_9_fu_1781_p2 = (lhs_V_9_fu_1773_p3 + mul_ln1393_9_reg_2906);

assign ret_V_fu_1410_p2 = (lhs_V_fu_1403_p3 + mul_ln1393_reg_2716);

assign sext_ln39_fu_500_p1 = sub_i_i226_fu_494_p2;

assign sub_i_i226_fu_494_p2 = (2'd1 - count_V);

assign sum_each_V_fu_2221_p4 = {{ret_V_20_fu_2216_p2[46:15]}};

assign tmp_17_fu_1415_p4 = {{ret_V_fu_1410_p2[46:15]}};

assign tmp_21_fu_1502_p4 = {{ret_V_2_fu_1497_p2[46:15]}};

assign tmp_25_fu_1589_p4 = {{ret_V_4_fu_1584_p2[46:15]}};

assign tmp_29_fu_1676_p4 = {{ret_V_6_fu_1671_p2[46:15]}};

assign tmp_33_fu_1763_p4 = {{ret_V_8_fu_1758_p2[46:15]}};

assign tmp_37_fu_1850_p4 = {{ret_V_10_fu_1845_p2[46:15]}};

assign tmp_41_fu_1937_p4 = {{ret_V_12_fu_1932_p2[46:15]}};

assign tmp_45_fu_2024_p4 = {{ret_V_14_fu_2019_p2[46:15]}};

assign tmp_49_fu_2119_p4 = {{ret_V_16_fu_2114_p2[46:15]}};

assign tmp_53_fu_2176_p4 = {{ret_V_18_fu_2171_p2[46:15]}};

assign trunc_ln1_fu_2235_p4 = {{ret_V_20_fu_2216_p2[37:15]}};

assign trunc_ln39_fu_522_p1 = sub_i_i226_fu_494_p2[0:0];

assign trunc_ln859_fu_2245_p1 = sum_V[22:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "low_pass_filter_second_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //low_pass_filter_second

